In [16]:
import requests

url = "https://apis.data.go.kr/B410001/trend-news"

params = {
    "serviceKey": "V/WBD6uRvTL7UmWfZq1iXcdUJSrzipq3qPcddtskwBuwLhZkHOXp7cLL6i4C41xqLbH7jtCT8QJ5MJCn3Cw32Q==",  # 공공데이터포털의 일반 인증키(Decoding)
    "type": "json",
    "numOfRows": 100,
    "pageNo": 1,
}

headers = {
    "User-Agent": "Mozilla/5.0"
}

res = requests.get(url, params=params, headers=headers, timeout=20)

print("status:", res.status_code)
print("final url:", res.url)
print("content-type:", res.headers.get("content-type"))
print(res.text[:1000])

status: 500
final url: https://apis.data.go.kr/B410001/trend-news?serviceKey=V%2FWBD6uRvTL7UmWfZq1iXcdUJSrzipq3qPcddtskwBuwLhZkHOXp7cLL6i4C41xqLbH7jtCT8QJ5MJCn3Cw32Q%3D%3D&type=json&numOfRows=100&pageNo=1
content-type: text/plain; charset=utf-8
Unexpected errors

# 전체 뉴스 저장

In [ ]:
import requests
import pandas as pd
import os
from dotenv import load_dotenv

load_dotenv()

SERVICE_KEY = os.getenv("SERVICE_KEY_DECODED")
url = "https://apis.data.go.kr/B410001/kotra_overseasMarketNews/ovseaMrktNews/ovseaMrktNews"

params = {
    "serviceKey": SERVICE_KEY,
    "type": "json",
    "numOfRows": 1000,
    "pageNo": 1,

    # # 선택 검색 조건
    # "search1": "일본",        # 국가명
    # "search2": "뷰티",        # 뉴스 제목
    # "search4": "20250501",   # 시작일
    # "search5": "",           # 산업분류 코드
    # "search6": "",           # Hot Clip
    # "search7": "20260504",   # 종료일
}

res = requests.get(url, params=params, timeout=10)
data = res.json()

print("status:", res.status_code)
print("url:", res.url)

In [ ]:
body = data["response"]["body"]
items = body["itemList"]["item"]

df = pd.DataFrame(items)

# 컬럼명 한글화
rename_cols = {
    "newsTitl": "뉴스제목",
    "kotraNewsUrl": "게시물 URL",
    "fileLink": "파일링크",
    "othbcDt": "뉴스게시일자",
    "natn": "국가",
    "regn": "지역",
    "ovrofInfo": "무역관정보",
    "newsWrterNm": "뉴스작성자명",
    "infoCl": "정보분류(메뉴명)",
    "indstCl": "산업분류",
    "indstCdList": "산업분류코드목록",
    "hsCdNm": "HS코드명",
    "cmdltNmKorn": "품목명한글",
    "cmdltNmEng": "품목명영문",
    "dataType": "저작권 정책",
    "bbstxSn": "게시글일련번호",
    "bbsSn": "정보분류(메뉴ID)",
    "jobSeNm": "일자리구분명",
}

df = df.rename(columns=rename_cols)
print("전체 건수:", body["totalCnt"])
df

In [ ]:
import requests
import pandas as pd
import os
import math
import time
import sqlite3
from dotenv import load_dotenv

load_dotenv()

SERVICE_KEY = os.getenv("SERVICE_KEY_DECODED")

url = "https://apis.data.go.kr/B410001/kotra_overseasMarketNews/ovseaMrktNews/ovseaMrktNews"

num_rows = 100

# 1페이지 호출해서 전체 건수 확인
params = {
    "serviceKey": SERVICE_KEY,
    "type": "json",
    "numOfRows": num_rows,
    "pageNo": 1,
}

rename_cols = {
    "newsTitl": "뉴스제목",
    "kotraNewsUrl": "게시물 URL",
    "fileLink": "파일링크",
    "othbcDt": "뉴스게시일자",
    "natn": "국가",
    "regn": "지역",
    "ovrofInfo": "무역관정보",
    "newsWrterNm": "뉴스작성자명",
    "infoCl": "정보분류(메뉴명)",
    "indstCl": "산업분류",
    "indstCdList": "산업분류코드목록",
    "hsCdNm": "HS코드명",
    "cmdltNmKorn": "품목명한글",
    "cmdltNmEng": "품목명영문",
    "dataType": "저작권 정책",
    "bbstxSn": "게시글일련번호",
    "bbsSn": "정보분류(메뉴ID)",
    "jobSeNm": "일자리구분명",
}

res = requests.get(url, params=params, timeout=30)
data = res.json()

body = data["response"]["body"]
total_cnt = int(body["totalCnt"])
total_pages = math.ceil(total_cnt / num_rows)

print("전체 건수:", total_cnt)
print("전체 페이지:", total_pages)


all_items = []

for page in range(1, total_pages + 1):
    params = {
        "serviceKey": SERVICE_KEY,
        "type": "json",
        "numOfRows": num_rows,
        "pageNo": page,
    }

    success = False

    for attempt in range(3):
        try:
            res = requests.get(url, params=params, timeout=30)
            data = res.json()

            items = data["response"]["body"]["itemList"]["item"]

            if isinstance(items, dict):
                items = [items]

            all_items.extend(items)

            print(f"{page}/{total_pages} 페이지 완료")
            success = True
            break

        except Exception as e:
            print(f"{page}페이지 오류, {attempt + 1}번째 재시도:", e)
            time.sleep(2)

    if not success:
        print(f"{page}페이지는 최종 실패. 다음 페이지로 넘어갑니다.")

    time.sleep(0.3)

df = pd.DataFrame(all_items)
df = df.rename(columns=rename_cols)

# SQLite 저장
conn = sqlite3.connect("kotra_news.db")
df.to_sql("kotra_news", conn, if_exists="replace", index=False)
conn.close()

# Excel 저장
df.to_excel("kotra_news.xlsx", index=False)

print("저장 완료")
print("수집 행 수:", len(df))

# 뉴스 분석

In [7]:
import pandas as pd

df = pd.read_excel("data/kotra_news.xlsx")

cols = ["지역", "국가", "산업분류", "정보분류(메뉴명)"]

for col in cols:
    print("=" * 80)
    print(f"[{col}]")
    print("전체 행 수:", len(df))
    print("결측치 개수:", df[col].isna().sum())
    print("결측치 비율:", round(df[col].isna().mean() * 100, 2), "%")
    print("unique 개수:", df[col].nunique(dropna=True))

    print("\n값별 개수:")
    print(df[col].value_counts(dropna=False))

================================================================================
[지역]
전체 행 수: 94572
결측치 개수: 8
결측치 비율: 0.01 %
unique 개수: 9

값별 개수:
지역
아시아         38650
유럽          22230
북미          11507
중남미          8753
중동           8014
아프리카         2898
대양주          2121
KOTRA 본사      389
NaN             8
전세계             2
Name: count, dtype: int64
================================================================================
[국가]
전체 행 수: 94572
결측치 개수: 770
결측치 비율: 0.81 %
unique 개수: 114

값별 개수:
국가
중국       12144
미국        9549
일본        5906
러시아연방     3449
인도        3225
         ...
바레인          1
예멘           1
엘살바도르        1
아이티          1
알바니아         1
Name: count, Length: 115, dtype: int64
================================================================================
[산업분류]
전체 행 수: 94572
결측치 개수: 26754
결측치 비율: 28.29 %
unique 개수: 2187

값별 개수:
산업분류
NaN                                                     26754
전자/전기                                                   16228
기타                                                       7254
산업일반                                                     5074
자동차/수송기기                                                 4781
                                                        ...
광물/에너지,철강/금속,기계류,자동차/수송기기,건설/인프라/플랜트,유통/물류                  1
섬유/패션,기계류,자동차/수송기기,전자/전기,의료바이오,환경,건설/인프라/플랜트,IT,산업일반        1
농림수산식품,자동차/수송기기,의료바이오,환경,유통/물류                              1
자동차/수송기기,건설/인프라/플랜트,금융                                      1
의료바이오,IT,문화콘텐츠                                              1
Name: count, Length: 2188, dtype: int64
================================================================================
[정보분류(메뉴명)]
전체 행 수: 94572
결측치 개수: 0
결측치 비율: 0.0 %
unique 개수: 10

값별 개수:
정보분류(메뉴명)
트렌드               34238
경제·무역             24800
투자진출              10955
현장·인터뷰            10356
통상·규제              6905
외부전문가 기고           2655
포토뉴스               2438
국별 주요산업            1928
현지정보(우크라이나 사태)      222
기획리포트                75
Name: count, dtype: int64

In [ ]:
import pandas as pd

df = pd.read_excel("kotra_news.xlsx")
df["뉴스게시일자"] = pd.to_datetime(df["뉴스게시일자"], errors="coerce")
df["연도"] = df["뉴스게시일자"].dt.year

# 연도별 뉴스 개수
year_counts = (
    df["연도"]
    .value_counts(dropna=False)
    .sort_index()
    .reset_index()
)

year_counts.columns = ["연도", "뉴스개수"]
year_counts

# 기사 본문 내용 저장

In [ ]:
import pandas as pd

df = pd.read_excel("data/kotra_news.xlsx")
df.info()

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

df = pd.read_excel("kotra_news.xlsx")
first_url = df.loc[0, "게시물 URL"] # 첫 번째 행의 게시물 URL

print(first_url)

In [ ]:
headers = {
    "User-Agent": "Mozilla/5.0"
}

res = requests.get(first_url, headers=headers, timeout=20)

print("status:", res.status_code)
print("url:", res.url)

In [ ]:
soup = BeautifulSoup(res.text, "html.parser")
keyword_area = soup.select_one("div.keywordArea")

if keyword_area:
    keywords = [a.get_text(strip=True) for a in keyword_area.select("a")]
else:
    keywords = []

print(keywords)

In [ ]:
view_txt = soup.select_one("div.view_txt")

if view_txt:
    body_text = view_txt.get_text(separator="\n", strip=True)
else:
    body_text = ""

print(body_text[:200])

In [ ]:
view_data = soup.select_one("div.view_txt div.viewDataWrap")

if view_data:
    body_text = view_data.get_text(separator="\n", strip=True)
else:
    body_text = ""

print(body_text[:200])

In [ ]:
result = {
    "게시물 URL": first_url,
    "키워드": keywords,
    "본문": body_text,
}

print("URL:", result["게시물 URL"])
print("키워드:", result["키워드"])
print("본문 앞부분:")
print(result["본문"][:1000])

## 전체 기사 본문 수집 파이프라인

In [ ]:
import re
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm.auto import tqdm

INPUT_XLSX = Path("data/kotra_news.xlsx")
PROGRESS_CSV = Path("data/kotra_news_body_progress.csv")
OUTPUT_CSV = Path("data/kotra_news_body.csv")

SAVE_EVERY = 1000
REQUEST_TIMEOUT = 20
URL_COL = "게시물 URL"
CSV_ENCODING = "utf-8-sig"

headers = {"User-Agent": "Mozilla/5.0"}
unsafe_csv_chars = re.compile(r"[\x00]")


def clean_text(value):
    if value is None:
        return ""
    return unsafe_csv_chars.sub("", str(value))


def save_csv(df, path):
    temp_path = path.with_name(path.stem + ".tmp" + path.suffix)
    df.to_csv(temp_path, index=False, encoding=CSV_ENCODING)
    temp_path.replace(path)


def fetch_article(url):
    res = requests.get(url, headers=headers, timeout=REQUEST_TIMEOUT)
    res.raise_for_status()

    soup = BeautifulSoup(res.text, "html.parser")

    keyword_area = soup.select_one("div.keywordArea")
    keywords = []
    if keyword_area:
        keywords = [a.get_text(strip=True) for a in keyword_area.select("a")]

    view_data = soup.select_one("div.view_txt div.viewDataWrap")
    view_txt = view_data or soup.select_one("div.view_txt")
    body_text = view_txt.get_text(separator="\n", strip=True) if view_txt else ""

    return clean_text(", ".join(keywords)), clean_text(body_text)


if PROGRESS_CSV.exists():
    df = pd.read_csv(PROGRESS_CSV, encoding=CSV_ENCODING, dtype=str, keep_default_na=False)
    print(f"이어하기: {PROGRESS_CSV}")
else:
    df = pd.read_excel(INPUT_XLSX, dtype=str).fillna("")
    print(f"새로 시작: {INPUT_XLSX}")

for col in ["키워드", "본문"]:
    if col not in df.columns:
        df[col] = ""

pending_mask = df["본문"].isna() | (df["본문"].astype(str).str.strip() == "")
pending_indexes = df.index[pending_mask].tolist()

success_count = 0
fail_count = 0
processed_since_save = 0
saved_batches = 0

pbar = tqdm(pending_indexes, desc="기사 본문 수집")

try:
    for idx in pbar:
        url = df.at[idx, URL_COL] if URL_COL in df.columns else ""

        try:
            if pd.isna(url) or not str(url).strip():
                raise ValueError("URL 없음")

            keywords, body_text = fetch_article(str(url).strip())
            if not body_text.strip():
                raise ValueError("본문 없음")

            df.at[idx, "키워드"] = keywords
            df.at[idx, "본문"] = body_text
            success_count += 1
            last_status = "success"

        except Exception as e:
            fail_count += 1
            last_status = f"fail: {type(e).__name__}"

        processed_since_save += 1
        pbar.set_postfix(success=success_count, fail=fail_count, saved=saved_batches, last=last_status)

        if processed_since_save >= SAVE_EVERY:
            save_csv(df, PROGRESS_CSV)
            saved_batches += 1
            processed_since_save = 0
            pbar.write(f"{success_count + fail_count}개 처리 후 저장 완료: {PROGRESS_CSV}")

except KeyboardInterrupt:
    print(f"중단됨. 다음 실행 시 마지막 저장 파일에서 이어합니다: {PROGRESS_CSV}")

else:
    save_csv(df, PROGRESS_CSV)
    save_csv(df, OUTPUT_CSV)
    print(f"완료: {OUTPUT_CSV}")

print(f"이어하기 파일: {PROGRESS_CSV}")

# OpenAI 임베딩 -> 성능 구림

In [ ]:
import pandas as pd

df = pd.read_csv("data/kotra_news_body.csv")
df.count()

/var/folders/wx/rj6wt5wn1yl8195jd9gqn5jc0000gn/T/ipykernel_58605/3072361545.py:3: DtypeWarning: Columns (0: 일자리구분명) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/kotra_news_body.csv")

품목명한글         23315
뉴스제목          94572
게시물 URL       94572
일자리구분명          908
HS코드명         23343
저작권 정책        94572
품목명영문         23315
지역            94564
파일링크          90405
산업분류          67818
산업분류코드목록      67818
무역관정보         93769
뉴스게시일자        94572
게시글일련번호       94572
뉴스작성자명        94572
정보분류(메뉴ID)    94572
정보분류(메뉴명)     94572
국가            93802
키워드           49125
본문            94550
dtype: int64

In [16]:
df = pd.read_csv("data/kotra_news_body.csv", encoding="utf-8-sig")
df.columns = df.columns.str.replace("\ufeff", "", regex=False).str.strip()

df = df[
    df["본문"].notna() &
    (df["본문"].astype(str).str.strip() != "")
].reset_index(drop=True)

# 일단 테스트용으로 첫 10개만
df_sample = df.iloc[:10]
df_sample

/var/folders/wx/rj6wt5wn1yl8195jd9gqn5jc0000gn/T/ipykernel_58605/856752178.py:1: DtypeWarning: Columns (0: 일자리구분명) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/kotra_news_body.csv", encoding="utf-8-sig")

,품목명한글,뉴스제목,게시물 URL,일자리구분명,HS코드명,저작권 정책,품목명영문,지역,파일링크,산업분류,산업분류코드목록,무역관정보,뉴스게시일자,게시글일련번호,뉴스작성자명,정보분류(메뉴ID),정보분류(메뉴명),국가,키워드,본문
0,"미용이나 메이크업용 제품류와 기초화장용 제품류[의약품은 제외하며, 선스크린(suns...",고물가와 경쟁 속 변화하는 러시아 뷰티 시장,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,3304,4유형,Beauty or make-up preparations and preparation...,유럽,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,생활소비재,I001198,노보시비르스크무역관,2026-05-04,240938,김하민,243,트렌드,러시아연방,"#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출",‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모...
1,NaN,"도미니카공화국, 플라스틱 제품류 수입, 유통 기업 대상 환경 규제 강화",https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,중남미,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,"화학,환경","I001212,I001203",산토도밍고무역관,2026-05-04,241022,Adriana Jimenez,242,경제·무역,도미니카공화국,"#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제",요약\n도미니카공화국은 2025년 12월 법률 제98-25호 시행을 통해 플라스틱·...
2,NaN,HORECA EXPO에서 살펴보는 러시아 외식산업 트렌드와 유망 분야,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,유럽,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,"농림수산식품,섬유/패션,생활소비재,유통/물류,관광/교육/서비스,산업일반","I001193,I001197,I001198,I001208,I001210,I001307",모스크바무역관,2026-05-04,240931,정의한,245,현장·인터뷰,러시아연방,"#러시아, #식품, #외식, #식당, #호텔, #레스토랑, #Horeca, #전시회...",<HORECA Expo 2026\n전시회\n개요\n>\n전시회명\nHORECA EX...
3,"미용이나 메이크업용 제품류와 기초화장용 제품류[의약품은 제외하며, 선스크린(suns...",[해외시장뉴스플러스] &lsquo;K-Lifestyle in Chennai&rsqu...,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,3304,4유형,Beauty or make-up preparations and preparation...,아시아,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,생활소비재,I001198,첸나이무역관,2026-05-04,240981,윤병은,243,트렌드,인도,"#뷰티, #화장품, #인도, #전자상거래, #온라인, #K-뷰티, #인플루언서, #인터뷰",인도\nK-\n뷰티 시장 확대\n인도 화장품 시장이 빠르게 커지고 있다. 시장조사 ...
4,NaN,2026 케냐 국제 투자 컨퍼런스를 통해 살펴본 케냐 투자유치 동향 및 전망,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,아프리카,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,산업일반,I001307,나이로비무역관,2026-05-04,241000,신정렬,322,투자진출,케냐,"#케냐, #투자, #컨퍼런스","최근 케냐는 '제조업 기반의 경제 성장'이라는 확고한 목표 아래, 파격적인 투자 환..."
5,기타,탄자니아 뷰티시장 성장세&hellip; K-뷰티 진출 기회 커진다,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,330499,4유형,Other\n,아프리카,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,생활소비재,I001198,다레살람무역관,2026-05-04,240920,이정훈,243,트렌드,탄자니아,"#K-뷰티, #스킨케어, #화장품시장, #탄자니아, #위조품","탄자니아 뷰티시장 개황\nStatista에 따르면, 탄자니아 코스메틱 시장은 202..."
6,NaN,방범방재종합전 2026 참관기,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,아시아,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,기타,I001211,오사카무역관,2026-05-04,240926,하마다유지,245,현장·인터뷰,일본,"#방재, #지진, #방범, #보안, #열사병",전시회 스케치\n<\n전시회 개요\n>\n전시회\n명\n개 최 장 소\nINTEX ...
7,"기초화장용 제품류,메이크업용 제품류",일본 남성 뷰티 시장 : 전 연령대로 확대,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,"3304991000,3304992000",4유형,"Skin care cosmetics\n,Make-up cosmetics\n",아시아,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,생활소비재,I001198,오사카무역관,2026-05-04,240772,김대수,243,트렌드,일본,"#남성, #화장품, #뷰티, #멘즈뷰티, #K-Beauty, #일본, #일본 시장","일본 남성 뷰티 시장, 2019년 278억 엔에서 2024년 497억 엔으로 1.8..."
8,NaN,"인력난 해결의 열쇠, 자동화 기술이 주도하는 일본 식품 산업의 변화",https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,아시아,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,"농림수산식품,기계류","I001193,I001199",후쿠오카무역관,2026-05-04,240791,김경미,243,트렌드,일본,"#푸드테크, #DX, #AI, #식품, #자동화, #로봇",일본\n식품 가치사슬 전반으로 확산되는 생산성 혁신 흐름\n현재 일본이 정의하는 푸...
9,파이프ㆍ보일러 동체ㆍ탱크ㆍ통이나 이와 유사한 물품에 사용하는 탭ㆍ코크ㆍ밸브와 이와 ...,"美 해양 기자재 시장, &#39;납품 후 끝&#39;은 옛말&hellip; 운영&m...",https://dream.kotra.or.kr/user/extra/kotranews...,NaN,"8481,7307",4유형,Tapsㆍ cocksㆍ valves and similar appliances for...,북미,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,"광물/에너지,건설/인프라/플랜트","I001195,I001204",달라스무역관,2026-05-04,241034,신지혜,243,트렌드,미국,"#offshore, #해양에너지, #기자재, #미국, #해양, #장비, #공급, #...","미국 해양에너지 산업은 저유가 기조와 글로벌 공급 과잉이 지속되는 가운데, 트럼프 ..."

In [24]:
from langchain_core.documents import Document

# 3. Document 만들기
docs = []

for idx, row in df_sample.iterrows():
    doc = Document(
        page_content=row["본문"],
        metadata={
            "row_id": idx,
            "url": row.get("게시물 URL", ""),
            "keywords": row.get("키워드", "")
        }
    )
    docs.append(doc)

docs[0:5]

[Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모는\n1\n조2000억\n루블\n(\n약\n144\n억 달러\n)\n로 전년 대비\n7%-8%\n증가했다\n. 반면\n판매되는 화장품\xa0수량은 감소세로\n, ‘Nilson’\n에 따르면 스킨케어 화장품 판매량은\n1\n년 만에\n13.3%, ‘\n헤어케어\n’\n는\n5.3%, ‘\n바디케어\n’\n는\n4.1%\n줄었다\n.\n시장 규모가 커졌음에도 판매량이 감소한\xa0주요 원인으로\xa0화장품\xa0가격의\xa0증가가 꼽힌다.\n<연도별 러시아 화장품 판매수량\n및 증가율>\n(단위: 십\n억 개\n)\n[자료\n: Businesstat.ru]\n오프라인 판매는 감소하는 반면\xa0온라인\xa0마켓플레이스에서의\xa0판매가\xa0증가하고 있다\n. ’25\n년 온라인\xa0소매기업\n‘Wildberries’\n의 스킨케어 화장품 매출은\xa0전년 대비\n28%,\n색조 화장품 매출은\n20%\n증가했다\n.\n온라인 소매점들은 프리미엄\n,\n친환경\n,\n아시아 브랜드 등 다양한 카테고리의 메뉴를 운영하며 소비자들을 유입시키고 있다\n.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.\n소비자의\xa0구매력\xa0약화는\xa0멀티기능성\n,\n가성비\n,\n현지\xa0브랜드\xa0선호를\xa0키웠고\n,\n이는\xa0제조와\xa0판매\xa0모두에서\xa0더\xa0촘촘한\xa0가치사슬\xa0대응을\xa0요구했다\n.\n소매 기업들이 화장품을 직접 제조해 판매하고\n제조사들이 자체 판매망을 구축해 제품을 판매하는 등\n,\n전통적인 기업 형태 구분이 모호해지고\n,\n가치 사슬이\xa0복잡해지는 양상이다\n.\n리테일러들이\nOEM\n을 통해 자체 브랜드 제품을 생산해 판매하고\n,\n별도 유통사들을 통해서만 제품을 공급하던 제조사들도 자체 온라인 마켓플레이스를 구축해 판매하고 있다\n.\n식료품 소매체인\n‘VKUSVILL’\n은 자체 브랜드의 미스트\n,\n핸드크림 등 제품을 화장품 전문 소매체인\n‘Letual’\n사이\n트\n를 통해 판매하고 있고\n,\n소비재\n·\n식료품 소매체인\n‘Magnit’\n도 자체 PB\xa0화장품을 화장품 소매체인\n‘\n골든 애플\n’\n온라인 스토어에서\xa0판매하고 있다\n.\n<뷰티체인\nLetual\n사이트에서 판매되는\nVkusvill(\n식품소매점\n)\n브랜드 화장품>\n* 주\n:\n번역기 통해 러시아어를 한국어로 변환\n[자료\n: Letual]\n로컬 브랜드 확산\n물류\n·\n관세\n·\n환율의\xa0급변\xa0상황에서 러시아\xa0브랜드\xa0공급은 지속 확대되고 있다\n.\n러시아\n산업통상부에 따르\n면\n,\n’\n25\n년 향수 및 화장품 시장에서 러시아 제품 점유율은\n68%\n이다\n.\n‘\nBusinessStat\n’\n에 따르면 러시아에서 생산된 스킨케어\n제품 개수는\n‘21\n년\n2\n억9000\n만\n개에서\n‘25\n년\n3\n억7000만\n개로\n26%\n증가했다\n.\n러시아 정부는\n’\n27\n년\n3\n월부터 모든 소비재 소매 체인점에서 러시아산 비식품 제품을 의무적으로 진열하게 하는 법안인 일명\n"\n러시아 제품 진열대\n"\n를 발표했는데 러시아제 화장품\n,\n향수를 우선 대상 제품으로 검토하고 있다\n.\n<\n러시아 상위\n10\n위\n화장품 제조사\n>\n(단위: 백만 루블)\n연번\n회사명\n개요\n지역\n홈페이지\n매출액\xa0(\'25년 기준)\n1\nFaberlic JSC\n화장품, 의류, 액세서리, 신발 및 기타 품목 제조\n모스크바\nfaberlic.com/ru/ru\n35,668.4\n2\nNTS Gradient LLC\n색조 및 스킨케어 화장품 독점 유통\n모스크바\nwww.gradient.ru\n29,739.88\n3\nUni\nc\no\nsmetic\nLLC\n헤어케어 및 염모제 생산\n상트페테르부르크\nestel.pro\n17,506.67\n4\nArnest JSC\n데오도란트, 안면·전신용 화장품, 식품 등 생산\n스타브로폴 지방 네비노미스크\nwww.arnest.ru\n17,455.63\n5\nZettek LLC\n물티슈 및 건티\n슈 생산\n칼루가 주\nzettek.ru\n9,914.62\n6\nSibair JSC\n스프레이 및 데오도란트 생산\n노보시비르스크\nwww.sibiar.ru\n7,654.56\n7\nGrand AV LLC\n냅킨\n및 마스크 생산\n툴라 주\nwww.grand-av.ru\n6,190.97\n8\nOrganic Pharmaceuticals LLC\n치약 제조\n노브고로드 주\nwww.splat.ru\n5,672.87\n9\nAct LLC\n안면, 전신 및 모발용 케어 화장품 제조\n모스크바\ntheact.ru\n5,402.55\n10\nBiopharmrus LLC\n화장품, 식품 첨가물 및 의\n료용품 OEM 생산\n모스크바주 포돌스크\nbiofarmrus.com\n5,323.84\n* 주: 일부 치약, 물티슈 등 생활소\n비재 제조 포함\n[자료: Gl\nobus]\n홈뷰티\n(a\nt\n‑\nhome beauty)\n확산\n,\n코스메슈티컬\n(\ncosmeceuticals)\n시장 성장\n러시아 뷰티 서비스 가격은 빠르게\xa0인상되고 있다\n. ‘Informer’\n에 따르면,\n’25\n년 헤어\n,\n스파\n,\n숍 등 뷰티 서비스 비용은 전년 대비\n10%-14%\n증가했다\n.\n부동산 임대료 증가\n,\n숙련 인력 급여 인상\n,\n영세업체\nVAT\n면제 한도 변경 등이 가격 인상의 주요 원인으로 꼽힌다.\n‘\n뷰티 기업 및 전문가 협회\n’\n회장인\n‘\n랴 소디코바\n’\n는\n“서비스\n가격 인상의 영향으로\n’\n25\n년\n9-12\n월 기간 러시아인들의 각종 뷰티 숍 방문 빈도가 전년 대비\n20-30%\n감소했다\n.”\n고 말한다\n.\n소비자들은 값비싼 미용 장비를 이용하거나 필러 등을 주입하는 대신 갈바닉\n, LED\n마스크 등 소형 미용 기기를 구입해 집에서 피부를 관리하기 시작했다\n.\n고급 스파 대신 아로마틱 화장품과 스파 용품을 구매해 집에서 목욕을 하는 추세도 나타나고 있다.\n<\n마이크로전류 제품\nMedicube(\n좌\n), LED\n마스크\nL&L SKIN(\n우\n)>\n[자료: Medicube, Ozon]\n노화를 미리 대비하는\n‘\n노화 예방\n’\n에 대한 관심도 높아졌다\n.\n젊은 소비자들 사이에서\xa0자외선 손상\n,\n콜라겐 감소\n,\n표정 주름\n,\n피부 지지대 약화가 주요 관심사로 부상하고 있다.\n‘\n겉만 예뻐 보이는 마사지\n’\n가 아니라 피부 속 림프 순환\n,\n부종 감소\n,\n독소\n·\n노폐물 배출을 돕는 마사지 서비스나 진동 치료가 증가하고 있다\n.\n주사 없이 히알루론산\n,\n비타민 등을 피부에 투입하는 더마드롭\n(Dermadrop),\n콜라겐 등의 생성을 돕는 생체활성화\n(Bioactivation)\n에 대한 관심도 높다\n.\n과학적으로 입증된 효능을 가진 이른 바 약국에서 판매되는 화장품인 코스메슈티컬\n(cosmeceuticals)\n판매량은 최근\n3\n년간 꾸준히 증가하고 있다\n.\n<러시아 연도별/월별 약국화장품 판매량>\n(단위: 십억\n루블\n)\n[자료\n: DSM Group]\n성분표 확인하는 소비자들, 친환경 오가닉 제품 인기\n시장 규모가 크진 않지만 친환경 오가닉 화장품도 견조한 성장을 이어가고 있다\n.\n제품 성분표에서 화학 첨가제 포함 유무를 확인하는 소비자가 늘고\n,\n그린워싱\n(\n위장환경주의\n)\n에 대한 관심도 높아져 국제\n친환경 제품 인증서를 받으려는 기업들도 많아지고 있다\n.\n천연 화장품 수요가 가장 큰 제품군은\n‘\n얼굴 케어\n’\n이며\n,\n황산염 무함유 샴푸\n,\n오일 함유 린스 등\n‘\n헤어 케어\n’\n에 대한 수요도 높다\n.\n립스틱 같은 제품에 천연 원료 함유나 포장 재활용 문구도 많이 나타난다\n.\n러시아 정부는\n"Organic"\n라벨을 도입하는 한편\n,\n’\n25.10\n월에\n‘\n예비 국가 표준\n’\n을 승인\n,\n특정 요건을 충족하는 제품에 한해\n‘\n자연\n’\n,\n‘\n유기농\n’\n,\n‘그린\n’\n등의 단어를 쓸 수 있도록\xa0하는\xa0규제를 준비하기 시작했다\n.\n<동물 테스트 반대 표방 러시아 천연 화장품 브랜드\nMatsesta>\n[자료: Matsesta]\n복고풍의 귀환과 스토리\xa0감성 마케팅\n뷰티 업계는 수년간 이어져 온\n‘\n클린 걸\n(Clean Girl)’\n과\n‘\n미니멀리즘\n’\n에서 벗어나\n,\n과감하고 다채로운\n2000\n년대 감성으로 회귀하고 있다\n.\n계속되는 러-우 사태가 과거에 대한 향수를 자극한 측면이\xa0있다\n.\n단순히 따라 하는 화장이나 꾸안꾸 스타일이 아닌\n,\xa01990\n년대의\xa0섹시함과\n‘\n개성 중심의 뷰티\n’\n가 주목받고 있다\n.\xa0특히\n젊은층에서\n2000\n년대 스타일의 글리터 섀도우\n,\n그라데이션 립 등이 유행이다\n. 최근\xa0러시아\n패션 브랜드\n‘Gloria Jeans’\n는 러시아\nSNS\n인\n‘VK’\n와\n2000\n년\nY2K\n를 주제로 한 콜라보레이션 마케팅을 진행했다\n.\n<\n‘Gloria Jeans’\n와\n‘VK.com’\n콜라보레이션\n>\n[자료: Gloria Jeans]\n기능이나 가격보다\n‘\n브랜드가 전하는 이야기\n’\n에 열광하는 소비자들이\xa0늘고 있다\n.\n단순한 상품 구매를 넘어\n,\n브랜드 철학을 공유하고 정서적인 만족을 얻을 수 있는\n‘\n감성 마케팅\n’\n과\n‘\n스토리텔링\n’\n을 원하는 고객들이 많다\n.\n러시아 기업\n‘Natura Siberica’\n는 러시아 전통 도자기\n‘\n그젤\n(Gzhel)’\n문양을 활용한 디자인을 통해 브랜드에 애국심과 민족적 정체성을 입혔다\n.\n러시아인의 향수와 문화적 자부심을 자극하는 감성 마케팅 사례로 꼽힌다\n.\n‘Erinel’\n사는\n‘\n엘프의 전설\n’\n이라는 독특한 세계관을 브랜드에 녹여냈다\n.\n엘프의 마법 이야기를 모든 제품과 디자인에 담아냈다\n.\n이러한 차별화된 세계관은 강력한 팬덤을 형성하는 원동력이 됐다\n.\n<러시아 전통 디자인을 차용한\nNatura Siberica,\n엘프 스토리를 활용한\n‘Erinel’>\n[자료: Natura Siberica, Erinel\n]\n마케팅 흐름은 이제\n‘\n성능과 효율\n’\n을 강조하던 시대에서\n‘\n공감과 가치\n’\n를 공유하는 시대로 넘어왔다\n.\n소비자는 입술을 붉게 칠하는 립스틱을 사는 것이 아니라\n,\n그 립스틱이 담고 있는 브랜드 철학을 자신의 라이프스타일에 입히고 있는 셈이다\n.\n피부 관리 시작한 러시아 남성들\n, K-Pop\n도 영향\n건강한 피부는 젊음과 성공의 상징이라는 인식이 남성들에게 확산되고 있다\n.\n‘\nInfoline\n’\n에 따르면\n’\n25\n년 남성 화장품 판매는 전년 대비\n20%\n증가했는데\n,\n이는 여성 제품 증가율\n(13%)\n보다 높은 수치다\n.\n‘\nCommerce\n’\n에 따르면,\n’\n25\n년 남성 화장품 부문에서 소매체인\n‘\nWildberries\n’\n는\n247\n억 루블\n(\n약\n2억9600만 달러\n)\n,\n‘\nOzon\n’\n은\n145\n억 루블\n(약\n1억7400만 달러\n)\n의 매출액을 기록했다\n.\n‘\nCollagene 3D Medical\n’\n사의 전무이사\n‘\n나제즈다 볼코바\n’\n는 무역관과의 인터뷰에서\n“최근\n러시아 남성들은\n셰\n이빙\xa0로션 뿐만 아니라\n,\n보습제\n,\n세럼\n,\n자외선차단제\n,\n화장품을 구매한다\n.”\n고\xa0언급했다\n. 한편\n뷰티체인\n‘\nIl De Bote\n’\n의 메이크업 아티스트인\n‘\n아나스타샤 율리나\n’\n는\n“\n남성들에게 안티 에이징 화장품이 인기\n”\n라면서\n“\n남성 화장품의 인기에\nK-Pop\n이 미친 영향을 무시할 수 없다.\n”\n고 밝혔다.\n<맥주 캔 디자인의 남성용 샤워젤 제품\n(\n좌\n), Wildberries\n남성용 화장품\xa0검색 결과\n(\n우\n)>\n[자료: Wildberries\n]\n뷰티 전문 리테일러들의 서비스 전문화와\nAI\xa0적용 확대\n화장품\xa0소매점들의 서비스는 더욱 전문화되고 있다\n.\n다양한 제품과 서비스에 대해\xa0충분한 사전 교육을 받은 종업원들이 먼저 고객에게 다가가 피부 컨디션을\xa0묻고 화장품을 추천한다\n.\n소비자들의 반응과 문의를 기다리던 과거와 달라진 모습이다\n.\n매\n장\n인\n테\n리\n어\n디\n자\n인도\n트\n렌\n드\n에\n맞\n게\n수시로\n바\n꾸\n고\n,\n브\n랜\n드\n와\n제\n품\n도\n소\n비\n자\n들\n이\n보\n기\n편\n하\n게\n분류해\xa0배치하고 있다.\xa0감\n각\n적인 디자인의\xa0각종\xa0특별 판촉\xa0공간, 체험존도\xa0운영한다.\n<Golden Apple 노보시비르스크 지점 내 제품 체험존>\n[자료: Golden Apple\n]\nAI 활용도 늘고 있다.\xa0AI를 통해\n피부 진단과 제품 선택을 지원하는\n‘BeautyScan’\n서비스는 소매체인\n‘Magnit Cosmetic’\n의\n2500\n개 매장에서 제공되고 있다\n.\n서비스 도입 이후 사용자들의 평균 구매 금액이\n29%\n증가했으며 매장 방문 빈도도 운영 전 대조군 대비\n35%\n증가한 것으로 나타났다\n.\n러시아 화장품 제조사이자 피부진단 기업인\n‘GELTEK’\n는 얼굴 이미지를 통해 피부 문제를 진단하는 러시아 최초의\nAI\n서비스\n‘Skin Assistant’\n를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>\n[자료: Skin Assiatant\n]\nK-Beauty 트렌드\xa0지속\n‘\nS&P Global\n’\n에 따르면,\n‘25\n년 러시아의 화장품\n(HS Code 3404)\n수입 규모는 약\n12\n억 달러로 전년 대비\n7.8%\n성장했다\n.\n이 중 한국산 화장품 수입액은\n3\n억6000만\n달러로 전년대비\n12%\n이상 성장\n,\n러시아 내\n1\n위 수입국 지위를 유지하고 있다\n. 2\n위인 프랑스\n(\n1\n억8000만\n달러\n)\n와는 약\n2\n배의 격차이다\n.\n’\n25\n년\n4\n월\n,\n러시아 정부는 비우호국산 화장품 및 향수에 대한 고율 관세 부과 대상에서 한국을 전격 제외했다\n.\n이에 따라\xa0과거에 부과되던\n35%\n의 고율 관세 대신\n,\n한국산 제품은\n6.5%\n의 표준 관세율을 적용받게 됐다\n.\n대상 품목은 향\n수\n,\n화장수\n,\n색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액\n(HS Code 3304:\n미용\n·\n메이크업용 및 기초화장품류\n)>\n(단위: US$ 천, %)\n순번\n국가\n수입액\n증가율\n2025/2024\n2023\n2024\n2025\n총액\n1,103,557\n1,103,011\n1,189,001\n7.80\n1\n대한민국\n316,157\n322,347\n361,229\n12.06\n2\n프랑스\n130,437\n148,342\n180,498\n21.68\n3\n중국\n122,882\n113,498\n155,169\n36.71\n4\n독일\n72,753\n85,998\n91,707\n6.64\n5\n폴란드\n138,545\n110,257\n85,555\n-22.40\n6\n이탈리아\n37,126\n83,896\n75,595\n-9.89\n7\n카자흐스탄\n25,240\n44,150\n62,459\n41.47\n8\n이스라엘\n40,646\n34,642\n33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]\n<화장품\xa0체인점 Golden\xa0Apple내\xa0한국화장품 섹션 중 일부>\n[자료:\nKOTRA\n노보시비르스크\n무역관 자체 촬영]\n시사점\n경제제재 이후 해외 브랜드 철수\n,\n병행수입\n,\n물류 상황 변화가\xa0겹치면서 러시아의 기존 수입 브랜드 유통 구조가 변화해왔다\n.\n이 과정에서 기존 소매업체들은 단순 판매보다 새로운 브랜드 포트폴리오 확보와 자체 대응이 중요해졌다\n.\n러시아 로컬 브랜드는 수요 공백을 메우며 빠르게 성장했고\n,\n일부는 생산까지 확대했다\n.\n러시아 시장에서는\n“\n매장에 올리는 것\n”\n보다\n“\n소비자의 욕실과 화장대에 들어가는 것\n”\n이 중요해졌다는 표현이 나올 정도로\n,\n브랜드 경쟁이 치열해졌다\n.\n이는 단순 유통보다 브랜드 소유와 제품 기획 역량이 중요해졌다는 의미이다\n.\n전시 고물가 추세가 지속되는 상황에서,\n우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다\n.\xa0독특한 성분과\xa0입증된\xa0효과를 갖춘 제품을\xa0지속적으로\xa0제안하고,\n인증, 물류, 마케팅\xa0등에서 체계적이고 신속한 대응 체계를 갖추는 한편, 브랜드가 가진 철학을 정직하고 일관성 있게 전달할 필요가 있다. 제품의 수출과 함께 K-Beauty의 프리미엄\xa0이미지를\xa0구축해 나갈\xa0시기이다.\n러시아 제조사\n‧\n뷰티전문체인과의 다각적인 파트너\n십\n구축\n,\nOEM\n‧\nODM\n협력\n,\n대형 디스트리뷰터 뿐만 아니라 지방의 유력 중견 바이어들과의\xa0네트워크\xa0확대\xa0등을 검토하고\n,\xa0홈뷰티,\n약국용 화장품\n,\n친환경\n,\n남성용\xa0제품 등\xa0성장 분야에도 관심을 가질 필요가 있다\n. 러시아\xa0수출을\xa0처음 추진하는\xa0기업들은 InterCharm(\nhttps://en.intercharm.ru/\n) 등\n전문\n전시\n회에\n참가하는 것도\n시장\xa0파악과\xa0관심\xa0바이어\xa0발굴에 효과적인\xa0방안이 될 수 있다.\n자료\n: Kommersant 등\nKOTRA\n노보시비르스크 무역관 자료 종합'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='요약\n도미니카공화국은 2025년 12월 법률 제98-25호 시행을 통해 플라스틱·발포(폼) 제품의 수입 및 유통 규제를 강화하였다. 동 법은 생분해성 인증 의무화와 생산자책임재활용제도(EPR) 확대를 주요 내용으로 하며, 발포폴리스티렌(EPS) 소재의 빨대·식기류·뚜껑·컵·용기 등은 적정한 환경 인증 없이는 수입이 금지된다. (법령 명칭 : 통합 고형폐기물 관리 및 공동처리법 개정안 (법률 제98-25호) / 현지어 명칭 : Ley Núm. 98-25 que modifica la Ley General de Gestión Integral y Coprocesamiento de Residuos Sólidos)\n2026\n년 2월 15일 동 법 발효 이후 관련 품목 통관 단계에서 도미니카공화국 관세청(DGA)이 인증 여부를 확인하고 있으며, 인증 서류 미비 시 통관 지연 또는 반송 사례가 발생하고 있는 것으로 파악된다.\n이번 규제는 환경정책의 변화에 그치지 않고 도미니카공화국 수입시장의 거래 조건에도 영향을 주고 있다. 한국 수출기업이 현지 바이어에게 직접 납품하는 구조라면 부담금이나 EPR 의무의 직접 대상은 아닐 수 있으나, 현지 수입업체의 규제 부담이 인증 자료 요청, 포장재 변경 요구, 가격 재협상 등의 형태로 공급업체에 전가될 수 있다.\n한편 기업 부담금 수준을 두고 현지 상공계와 정부·국회 간 협의가 진행 중이다(2026년 4월 현재). 부담금 체계는 변동 가능성이 있으나, 수입 금지 및 인증 의무화 조항은 그대로 적용되고 있어 대 도미니카공화국 수출기업 그리고 현지에 진출한 기업들의 지속적인 모니터링과 대응이 요구된다.\n개요\n법률 제98-25호는 기존 통합 고형폐기물 관리법(제225-20호)을 개정한 것으로, 2025년 12월 15일 공포되었다. 기존 법이 폐기물 관리 일반 기준에 초점을 맞춘 것과 달리, 개정법은 소재(material) 단위로 규제 대상을 설정한다. 특정 산업에 한정되지 않고, 발포 또는 비생분해성 플라스틱 소재를 사용하는 모든 제품이 규제 검토 대상에 포함된다. 이에 따라 완제품 수출기업뿐 아니라 현지 제조업체에 포장재나 부자재를 공급하는 기업도 영향권에 놓일 수 있다.\n규제 대상 주요 품목은 다음과 같다.\n폼(발포폴리스티렌, EPS) 소재 : 빨대·포크 나이프·숟가락·뚜껑·컵 등 (2026.02.15부터 즉시 수입 금지, 인증 없는 경우)\n일반 플라스틱 소재 : 빨대·포크 나이프·숟가락 (법 시행 후 12개월 이내 유통 금지, 인증 없는 경우)\n일회용 비닐봉투 : 법 시행 후 12개월 이내 무상 제공 금지\n규제 예외 품목으로는 의료·병원·실험실용 플라스틱 용기, 도로공사 및 건설용 플라스틱이 인정된다.\n또한 경첩형 뚜껑이 일체형으로 부착된 폼 식품 용기(예: 힌지 뚜껑 도시락 용기)는 유통 금지 조항에서 예외로 명시되어 있다.\n다만 예외 인정을 위해서는 해당 사유를 설명하는 서류 준비가 필요하다.\n생분해성 인증 기준은 시험기관의 검증을 통해 1년 내 최소 20%, 또는 최대 5년 내 9\n0% 이상의 분해율을 충족해야 한다\n.\n다만\xa0도미니카공화국품질원(INDOCAL)이\xa0세부\xa0기술\xa0기준\xa0및\xa0인증\xa0검증\xa0절차는\xa0아직\xa0마련\xa0중에\xa0있어,\xa0통관\xa0현장에서는 기준 적용 방식 등 관련하여 다소간의 혼선이 빚어질 수 있다. 현재\n국제\n규격에\n따른\n해외\n인증이\xa0다소\n광범위하게\n인정되고\xa0있으나,\xa0추후\xa0기준과\xa0절차\xa0정립\xa0후에는\xa0항목별로\xa0정확한\xa0준용이\xa0필요할\xa0것으로\xa0보인다.\n동\n법이 권장하는 대체 소재로는 종이, 재활용·생분해성 판지, 사탕수수\xa0부산\n물\n(bagasse), 대나무, 식물성 섬유, 퇴비화 가능 소재(compostable), 인증된 생분해성 소재, 재사용 가능 용기 등이 있다.\n집행\n기관\n관련,\n관세청(DGA)이\n통관 시\n인증\n서류를\n확인하고, 도미니카공화국품질원(INDOCAL)이 기술 검증을 지원하며, 환경부(Ministerio de Medio Ambiente y Recursos Naturales)가 제\n도\n전반의\n준수를\n감독한다.\n제도 시행 및 단계별 이행 일정\n동 법은 수입 절차와 국내 시장 운영 전반에 영향을 미치는 단계적 시행 조치를 규정하고 있다.\n<법령 시행 관련 일정>\n구분\n시행일\n주요 내용\n법률 제98-25호 시행\n2025.12.15\n개정된 폐기물관리 체계 시행\n폼 제품 수입금지\n2026.02.15\n빨대·식기·뚜껑·컵 등 미인증폼 제품 수입 금지\n폐기물 배출자등록\n2026.06.15\n환경부 대상사업자 등록 의무화\n일반 플라스틱식기·빨대 유통 금지\n2026.12.15\n미인증 플라스틱빨대·포크·숟가락·나이프유통 금지\n생산자책임재활용제도(Extended Produce Responsibility) 관리계획 제출\n2026.12.15\n폐기물 관리계획제출 의무\n무상 비닐봉투제공 금지\n2026.12.15\n일회용 비닐봉투무상 제공 금지\n발포 제품 대체전환\n2027.12.15\n친환경 대체소재로 전환\n지자체 분리배출프로그램\n2028.12.15\n지방정부 선택적수거 프로그램 확대\n실무적으로는 법률상 일정과 실제 통관·인증 운용 사이에 차이가 발생할 수 있다. INDOCAL의 세부 기술 기준이 확정되는 과정에서 혼선이 발생할 가능성이 있으므로, 현지 바이어가 실제로 어떤 서류를 요구받고 있는지를 확인하는 것이 단순히 법률 시행일을 확인하는 것보다 실질적인 대응에 도움이 될 것으로 사료된다.\n생산자책임재활용제도(EPR) 및 기업 부담금 관련 현황\n강화된 제도 하에서, 도미니카공화국 시장에 규제 대상 소재를 유통하는 기업은 수거, 재활용 등 사후 폐기물 관리에 대한 책임을 부담한다. 비닐봉투·플라스틱병 생산자는 법 시행 후 12개월 이내에 폐기물 회수·처리·처분 프로그램에 참여해야 한다. 한국에서 도미니카공화국으로 제품을 수출하는 기업이 곧바로 현지 부담금 납부 대상이 되는 구조는 아닌 것으로 파악된다. 다만 현지 수입업체, 유통업체, 제조업체가 관련 의무와 부담금을 부담하게 되면, 해당 비용이 인증 자료 요청, 발주 축소, 포장재 변경 요구, 가격 재협상 등의 형태로 한국 공급업체에 전가될 수 있다.\n동 법령을 통해 정부는 기업의 연간 매출액을 기준으로 산정되는 특별부담금(Contribución Especial) 제도를 도입하였다. 이 부담금은 EPR 의무 대상인 생산자·수입자·유통업자에 한정되지 않으며, 도미니카공화국 내에 등록된 모든 공·사법인(todas las personas jurídicas, públicas y privadas) 에 적용된다. 즉, 플라스틱 제품을 직접 생산하거나 수입하지 않더라도, 사업 운영 과정에서 폐기물을 발생시키는 법인이라면 납부 의무를 지게 된다. 국세청(DGII)이 안내한 바에 따르면 부담금은 연간 매출액 구간에 따라 RD$3,000에서 RD$675,000(약 50~11,250달러) 수준으로 규정되어 있으며, 수익 발생 여부와 관계없이 의무 납부 구조로 설계되어 있다. 이에 대해 도미니카공화국 산업협회(AIRD), 자유무역지대협회(Adozona), 상인연합회 등 주요 경제단체는 매출액 기준 부과 방식의 형평성 문제를 지적하고 있다. 매출이 유사하더라도 실제 폐기물 배출량은 업종에 따라 크게 다를 수 있어, 현행 구조가 조세 비례 원칙에 반한다는 것이 업계의 주된 주장이다.\n이러한 흐름을 반영하여, 2026년 4월 야당 상원 원내대표 등은 현행 매출액 중심의 균일 부담 구조를 폐기물 실제 배출량과 기업의 실질 부담 능력을 기준으로 전환하는 개정안을 상원에 제출하였다. 동 개정안은 중소기업의 부담을 경감하고 대형 폐기물 배출 사업자의 기여 비율을 높이는 방향으로 설계된 것으로 알려지고 있다. 정부 측도 2026년 4월 기준 해당 연도 특별부담금 징수를 일시 유예하고 조만간 의회에 개정안을 제출할 방침임을 밝혔다. 부담금 체계는 변동 가능성이 있으나, 폐기물 관리계획 제출 등 핵심사항에 대한 준수 의무는 현재도 유효하다.\n시장 반응\n수입 현장의 혼선\n2026\n년 2월 15일 수입 금지 조항 발효 이후, 생분해성 인증서를 확보하지 못한 상태에서 선적이 진행된 화물이 통관 보류 또는 반송 처리되는 사례가 발생하였다. INDOCAL의 기술 기준이 아직 확정되지 않은 상황에서, 어떤 인증서를 어떤 형식으로 제출해야 하는지에 관한 명확한 가이드라인이 부재하여 현지 통관 담당자들도 개별 건마다 판단이 엇갈리는 상황으로 알려진다. 바이어가 "통관에서 처리하겠다"고 말하더라도, 실제 통관 현장에서 인증서 또는 소재 자료가 요구될 경우 대응이 늦어질 수 있다는 점을 고려할 필요가 있다. 통관시에 현지 관청에서 요구하는 서류를 100% 충족할 수 없다 하더라도 직/간접적인 생분해성 인증 문서 등을 첨부하여 제시해야 하는 것으로 파악된다.\n플라스틱 뚜껑 수입 제한\n현지 산업계가 민감하게 반응한 품목 중 하나는 플라스틱 뚜껑이다. 도미니카공화국 산업협회(AIRD)는 식품·음료·주류·제약 분야에서 사용되는 플라스틱 뚜껑의 상당 부분이 현지에서 생산되지 않아 미국·유럽 등 수입에 의존하고 있는데, 대체재 없이 수입 금지가 적용될 경우 이들 산업 전반에 수급 차질이 발생할 수 있다고 경고하였다. 특히 의약품용 플라스틱 뚜껑과 포장 부품은 멸균성, 밀봉성, 아동 안전 기능 등 전문 요건을 갖춘 부품으로, 일반 플라스틱과 동일하게 규제 대상으로 취급할 경우 의약품 생산과 공급에도 영향을 줄 수 있다는 우려가 업계로부터 제기되었다.\n조달 전략 변화\n통관 지연 또는 반송 가능성에 대한 우려로, 현지 유통업체들은 기존 플라스틱 제품에 대한 신규 발주를 줄이고 인증 준수 여부를 우선 고려하는 조달 전략을 검토하고 있다. 가격이 낮더라도 인증 문서가 불명확한 공급업체는 선호도가 낮아지는 반면, 인증 자료와 소재 정보를 선제적으로 제공하는 공급업체가 거래 유지 및 신규 바이어 발굴에서 유리한 위치를 점하고 있는 것으로 파악된다. 콜롬비아 등 중남미 지역 공급업체들은 이미 인증을 갖춘 제품을 앞세워 운송 기간 단축 이점과 함께 시장 점유율 확대에 나서고 있다\n.\n대체 소재 수요 증가\n발포폴리스티렌(폼) 제품 규제에 따라 외식업계, 특히 \'꼬미다 델 디아(Comida del día, 일일 정식)\' 업계를 중심으로 대체 포장재 수요가 형성되고 있다. 다만 도미니카공화국 시장은 가격 민감도가 높고, 외식·배달용 포장재에 대해서는 내열성, 누수 방지, 보온성 등 기능 요건도 중요하게 작용한다. 친환경 소재라는 점만으로 시장 진입이 용이해진다고 보기는 어렵고, 현장에서 소화할 수 있는 가격이 우선시 되고 있다.\n시사점\n도미니카공화국의 이번 규제 강화는 수입 상품의 소재 구성과 인증 요건을 직접적으로 변화시키는 시장 변화이다. 플라스틱·발포 소재 제품을 현지에 수출 중이거나 진출을 검토 중인 기업은 아래 사항을 점검할 필요가 있다.\n제품별 규제\n적용 여부 우선 확인\n:\n플라스틱 빨대·식기류·뚜껑, 폼 컵·용기, 비닐봉투, 식품·외식용 포장재를 취급하는 기업은 해당 제품이 규제 대상인지, 예외 대상인지, 또는 인증으로 대응 가능한지를 현지 바이어 또는 통관 대리인과 함께 확인하는 것이 필요하다. 의료·실험실용 제품의 경우 예외가 인정될 수 있으나, 이 경우에도 예외 사유를 설명하는 서류를 사전에 준비해 두는 것이 바람직하다.\n인증서 외 기술 문서 패키지 준비\n:\n인증서만 보유하는 것으로는 충분하지 않을 수 있다. 현지 수입업체가 통관 단계에서 실제로 활용할 수 있도록 제품별 소재 설명서, 생분해성 시험성적서, 인증기관 정보, 시험 방법, 인증 유효기간 등을 스페인어 또는 영어로 함께 준비해 두는 것이 통관 대응 부담을 줄이는 데 도움이 된다.\n대체 포장재 공급 기업의 기회 :\n종이 기반 식품 포장재, 생분해성 소재, 재사용 가능 용기 등 인증을 갖춘 친환경 제품군을 보유한 기업에게는 시장 진입의 기회가 존재한다. 다만 현지 시장 특성상 기능성, 안정 공급, 특히 가격 경쟁력을 함께 제시하는 것이 중요하다.\n현지 법인·유통망 운영 기업의 검토 사항 :\n현지에서 수입자 역할을 맡는 구조라면 EPR 프로그램 참여 의무, 폐기물 관리계획 제출, 특별부담금 납부 등이 직접적인 비용 요인이 될 수 있다. 단순 수출 기업과 달리 현지 법인이나 창고를 운영하는 경우에는 이를 사업 계획에 별도 항목으로 반영해 두는 것이 필요하다고 사료된다.\n부담금 제도 및 규제 동향 지속 모니터링 :\n특별부담금 체계는 국회 개정 논의가 진행 중으로 변동 가능성이 있다. 현지 유통 파트너의 비용 구조 변화가 납품 조건에 영향을 줄 수 있어, 협의 결과를 지속적으로 확인하는 것이 필요하다. 다만 부담금 논의와 무관하게 플라스틱·폼 제품에 대한 인증 및 수입 규제의 방향성 자체는 강화 기조를 유지하고 있다.\n자료:\xa0도미니카공화국 국세청(DGII), 품질원(INDOCAL), 관세청(DGA), 환경부(Ministerio de Medio Ambiente y Recursos Naturales), 도미니카공화국 산업협회(AIRD), 현지 언론, 바이어/국내기업 인터뷰 등'),

In [26]:
from langchain_text_splitters import CharacterTextSplitter

# 4. Chunking
splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=600,
    chunk_overlap=100,
    length_function=len
)

split_docs = splitter.split_documents(docs)
split_docs[0:30]

Created a chunk of size 637, which is longer than the specified 600

[Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모는\n1\n조2000억\n루블\n(\n약\n144\n억 달러\n)\n로 전년 대비\n7%-8%\n증가했다\n. 반면\n판매되는 화장품\xa0수량은 감소세로\n, ‘Nilson’\n에 따르면 스킨케어 화장품 판매량은\n1\n년 만에\n13.3%, ‘\n헤어케어\n’\n는\n5.3%, ‘\n바디케어\n’\n는\n4.1%\n줄었다\n.\n시장 규모가 커졌음에도 판매량이 감소한\xa0주요 원인으로\xa0화장품\xa0가격의\xa0증가가 꼽힌다.\n<연도별 러시아 화장품 판매수량\n및 증가율>\n(단위: 십\n억 개\n)\n[자료\n: Businesstat.ru]\n오프라인 판매는 감소하는 반면\xa0온라인\xa0마켓플레이스에서의\xa0판매가\xa0증가하고 있다\n. ’25\n년 온라인\xa0소매기업\n‘Wildberries’\n의 스킨케어 화장품 매출은\xa0전년 대비\n28%,\n색조 화장품 매출은\n20%\n증가했다\n.\n온라인 소매점들은 프리미엄\n,\n친환경\n,\n아시아 브랜드 등 다양한 카테고리의 메뉴를 운영하며 소비자들을 유입시키고 있다\n.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.\n소비자의\xa0구매력\xa0약화는\xa0멀티기능성\n,\n가성비\n,\n현지\xa0브랜드\xa0선호를\xa0키웠고\n,\n이는\xa0제조와\xa0판매\xa0모두에서\xa0더\xa0촘촘한\xa0가치사슬\xa0대응을\xa0요구했다\n.\n소매 기업들이 화장품을 직접 제조해 판매하고\n제조사들이 자체 판매망을 구축해 제품을 판매하는 등\n,\n전통적인 기업 형태 구분이 모호해지고\n,\n가치 사슬이\xa0복잡해지는 양상이다\n.\n리테일러들이\nOEM\n을 통해 자체 브랜드 제품을 생산해 판매하고\n,\n별도 유통사들을 통해서만 제품을 공급하던 제조사들도 자체 온라인 마켓플레이스를 구축해 판매하고 있다\n.\n식료품 소매체인\n‘VKUSVILL’\n은 자체 브랜드의 미스트\n,\n핸드크림 등 제품을 화장품 전문 소매체인\n‘Letual’\n사이\n트\n를 통해 판매하고 있고\n,\n소비재\n·\n식료품 소매체인\n‘Magnit’\n도 자체 PB\xa0화장품을 화장품 소매체인\n‘\n골든 애플\n’\n온라인 스토어에서\xa0판매하고 있다\n.\n<뷰티체인\nLetual\n사이트에서 판매되는\nVkusvill(\n식품소매점\n)\n브랜드 화장품>\n* 주\n:'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘\n골든 애플\n’\n온라인 스토어에서\xa0판매하고 있다\n.\n<뷰티체인\nLetual\n사이트에서 판매되는\nVkusvill(\n식품소매점\n)\n브랜드 화장품>\n* 주\n:\n번역기 통해 러시아어를 한국어로 변환\n[자료\n: Letual]\n로컬 브랜드 확산\n물류\n·\n관세\n·\n환율의\xa0급변\xa0상황에서 러시아\xa0브랜드\xa0공급은 지속 확대되고 있다\n.\n러시아\n산업통상부에 따르\n면\n,\n’\n25\n년 향수 및 화장품 시장에서 러시아 제품 점유율은\n68%\n이다\n.\n‘\nBusinessStat\n’\n에 따르면 러시아에서 생산된 스킨케어\n제품 개수는\n‘21\n년\n2\n억9000\n만\n개에서\n‘25\n년\n3\n억7000만\n개로\n26%\n증가했다\n.\n러시아 정부는\n’\n27\n년\n3\n월부터 모든 소비재 소매 체인점에서 러시아산 비식품 제품을 의무적으로 진열하게 하는 법안인 일명\n"\n러시아 제품 진열대\n"\n를 발표했는데 러시아제 화장품\n,\n향수를 우선 대상 제품으로 검토하고 있다\n.\n<\n러시아 상위\n10\n위\n화장품 제조사\n>\n(단위: 백만 루블)\n연번\n회사명\n개요\n지역\n홈페이지\n매출액\xa0(\'25년 기준)\n1\nFaberlic JSC\n화장품, 의류, 액세서리, 신발 및 기타 품목 제조\n모스크바\nfaberlic.com/ru/ru'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content="연번\n회사명\n개요\n지역\n홈페이지\n매출액\xa0('25년 기준)\n1\nFaberlic JSC\n화장품, 의류, 액세서리, 신발 및 기타 품목 제조\n모스크바\nfaberlic.com/ru/ru\n35,668.4\n2\nNTS Gradient LLC\n색조 및 스킨케어 화장품 독점 유통\n모스크바\nwww.gradient.ru\n29,739.88\n3\nUni\nc\no\nsmetic\nLLC\n헤어케어 및 염모제 생산\n상트페테르부르크\nestel.pro\n17,506.67\n4\nArnest JSC\n데오도란트, 안면·전신용 화장품, 식품 등 생산\n스타브로폴 지방 네비노미스크\nwww.arnest.ru\n17,455.63\n5\nZettek LLC\n물티슈 및 건티\n슈 생산\n칼루가 주\nzettek.ru\n9,914.62\n6\nSibair JSC\n스프레이 및 데오도란트 생산\n노보시비르스크\nwww.sibiar.ru\n7,654.56\n7\nGrand AV LLC\n냅킨\n및 마스크 생산\n툴라 주\nwww.grand-av.ru\n6,190.97\n8\nOrganic Pharmaceuticals LLC\n치약 제조\n노브고로드 주\nwww.splat.ru\n5,672.87\n9\nAct LLC\n안면, 전신 및 모발용 케어 화장품 제조\n모스크바"),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='치약 제조\n노브고로드 주\nwww.splat.ru\n5,672.87\n9\nAct LLC\n안면, 전신 및 모발용 케어 화장품 제조\n모스크바\ntheact.ru\n5,402.55\n10\nBiopharmrus LLC\n화장품, 식품 첨가물 및 의\n료용품 OEM 생산\n모스크바주 포돌스크\nbiofarmrus.com\n5,323.84\n* 주: 일부 치약, 물티슈 등 생활소\n비재 제조 포함\n[자료: Gl\nobus]\n홈뷰티\n(a\nt\n‑\nhome beauty)\n확산\n,\n코스메슈티컬\n(\ncosmeceuticals)\n시장 성장\n러시아 뷰티 서비스 가격은 빠르게\xa0인상되고 있다\n. ‘Informer’\n에 따르면,\n’25\n년 헤어\n,\n스파\n,\n숍 등 뷰티 서비스 비용은 전년 대비\n10%-14%\n증가했다\n.\n부동산 임대료 증가\n,\n숙련 인력 급여 인상\n,\n영세업체\nVAT\n면제 한도 변경 등이 가격 인상의 주요 원인으로 꼽힌다.\n‘\n뷰티 기업 및 전문가 협회\n’\n회장인\n‘\n랴 소디코바\n’\n는\n“서비스\n가격 인상의 영향으로\n’\n25\n년\n9-12\n월 기간 러시아인들의 각종 뷰티 숍 방문 빈도가 전년 대비\n20-30%\n감소했다\n.”\n고 말한다\n.'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘\n랴 소디코바\n’\n는\n“서비스\n가격 인상의 영향으로\n’\n25\n년\n9-12\n월 기간 러시아인들의 각종 뷰티 숍 방문 빈도가 전년 대비\n20-30%\n감소했다\n.”\n고 말한다\n.\n소비자들은 값비싼 미용 장비를 이용하거나 필러 등을 주입하는 대신 갈바닉\n, LED\n마스크 등 소형 미용 기기를 구입해 집에서 피부를 관리하기 시작했다\n.\n고급 스파 대신 아로마틱 화장품과 스파 용품을 구매해 집에서 목욕을 하는 추세도 나타나고 있다.\n<\n마이크로전류 제품\nMedicube(\n좌\n), LED\n마스크\nL&L SKIN(\n우\n)>\n[자료: Medicube, Ozon]\n노화를 미리 대비하는\n‘\n노화 예방\n’\n에 대한 관심도 높아졌다\n.\n젊은 소비자들 사이에서\xa0자외선 손상\n,\n콜라겐 감소\n,\n표정 주름\n,\n피부 지지대 약화가 주요 관심사로 부상하고 있다.\n‘\n겉만 예뻐 보이는 마사지\n’\n가 아니라 피부 속 림프 순환\n,\n부종 감소\n,\n독소\n·\n노폐물 배출을 돕는 마사지 서비스나 진동 치료가 증가하고 있다\n.\n주사 없이 히알루론산\n,\n비타민 등을 피부에 투입하는 더마드롭\n(Dermadrop),\n콜라겐 등의 생성을 돕는 생체활성화\n(Bioactivation)\n에 대한 관심도 높다\n.'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n주사 없이 히알루론산\n,\n비타민 등을 피부에 투입하는 더마드롭\n(Dermadrop),\n콜라겐 등의 생성을 돕는 생체활성화\n(Bioactivation)\n에 대한 관심도 높다\n.\n과학적으로 입증된 효능을 가진 이른 바 약국에서 판매되는 화장품인 코스메슈티컬\n(cosmeceuticals)\n판매량은 최근\n3\n년간 꾸준히 증가하고 있다\n.\n<러시아 연도별/월별 약국화장품 판매량>\n(단위: 십억\n루블\n)\n[자료\n: DSM Group]\n성분표 확인하는 소비자들, 친환경 오가닉 제품 인기\n시장 규모가 크진 않지만 친환경 오가닉 화장품도 견조한 성장을 이어가고 있다\n.\n제품 성분표에서 화학 첨가제 포함 유무를 확인하는 소비자가 늘고\n,\n그린워싱\n(\n위장환경주의\n)\n에 대한 관심도 높아져 국제\n친환경 제품 인증서를 받으려는 기업들도 많아지고 있다\n.\n천연 화장품 수요가 가장 큰 제품군은\n‘\n얼굴 케어\n’\n이며\n,\n황산염 무함유 샴푸\n,\n오일 함유 린스 등\n‘\n헤어 케어\n’\n에 대한 수요도 높다\n.\n립스틱 같은 제품에 천연 원료 함유나 포장 재활용 문구도 많이 나타난다\n.\n러시아 정부는\n"Organic"\n라벨을 도입하는 한편\n,\n’\n25.10\n월에\n‘\n예비 국가 표준\n’'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n립스틱 같은 제품에 천연 원료 함유나 포장 재활용 문구도 많이 나타난다\n.\n러시아 정부는\n"Organic"\n라벨을 도입하는 한편\n,\n’\n25.10\n월에\n‘\n예비 국가 표준\n’\n을 승인\n,\n특정 요건을 충족하는 제품에 한해\n‘\n자연\n’\n,\n‘\n유기농\n’\n,\n‘그린\n’\n등의 단어를 쓸 수 있도록\xa0하는\xa0규제를 준비하기 시작했다\n.\n<동물 테스트 반대 표방 러시아 천연 화장품 브랜드\nMatsesta>\n[자료: Matsesta]\n복고풍의 귀환과 스토리\xa0감성 마케팅\n뷰티 업계는 수년간 이어져 온\n‘\n클린 걸\n(Clean Girl)’\n과\n‘\n미니멀리즘\n’\n에서 벗어나\n,\n과감하고 다채로운\n2000\n년대 감성으로 회귀하고 있다\n.\n계속되는 러-우 사태가 과거에 대한 향수를 자극한 측면이\xa0있다\n.\n단순히 따라 하는 화장이나 꾸안꾸 스타일이 아닌\n,\xa01990\n년대의\xa0섹시함과\n‘\n개성 중심의 뷰티\n’\n가 주목받고 있다\n.\xa0특히\n젊은층에서\n2000\n년대 스타일의 글리터 섀도우\n,\n그라데이션 립 등이 유행이다\n. 최근\xa0러시아\n패션 브랜드\n‘Gloria Jeans’\n는 러시아\nSNS\n인\n‘VK’\n와\n2000\n년\nY2K\n를 주제로 한 콜라보레이션 마케팅을 진행했다\n.\n<'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='. 최근\xa0러시아\n패션 브랜드\n‘Gloria Jeans’\n는 러시아\nSNS\n인\n‘VK’\n와\n2000\n년\nY2K\n를 주제로 한 콜라보레이션 마케팅을 진행했다\n.\n<\n‘Gloria Jeans’\n와\n‘VK.com’\n콜라보레이션\n>\n[자료: Gloria Jeans]\n기능이나 가격보다\n‘\n브랜드가 전하는 이야기\n’\n에 열광하는 소비자들이\xa0늘고 있다\n.\n단순한 상품 구매를 넘어\n,\n브랜드 철학을 공유하고 정서적인 만족을 얻을 수 있는\n‘\n감성 마케팅\n’\n과\n‘\n스토리텔링\n’\n을 원하는 고객들이 많다\n.\n러시아 기업\n‘Natura Siberica’\n는 러시아 전통 도자기\n‘\n그젤\n(Gzhel)’\n문양을 활용한 디자인을 통해 브랜드에 애국심과 민족적 정체성을 입혔다\n.\n러시아인의 향수와 문화적 자부심을 자극하는 감성 마케팅 사례로 꼽힌다\n.\n‘Erinel’\n사는\n‘\n엘프의 전설\n’\n이라는 독특한 세계관을 브랜드에 녹여냈다\n.\n엘프의 마법 이야기를 모든 제품과 디자인에 담아냈다\n.\n이러한 차별화된 세계관은 강력한 팬덤을 형성하는 원동력이 됐다\n.\n<러시아 전통 디자인을 차용한\nNatura Siberica,\n엘프 스토리를 활용한\n‘Erinel’>'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n이러한 차별화된 세계관은 강력한 팬덤을 형성하는 원동력이 됐다\n.\n<러시아 전통 디자인을 차용한\nNatura Siberica,\n엘프 스토리를 활용한\n‘Erinel’>\n[자료: Natura Siberica, Erinel\n]\n마케팅 흐름은 이제\n‘\n성능과 효율\n’\n을 강조하던 시대에서\n‘\n공감과 가치\n’\n를 공유하는 시대로 넘어왔다\n.\n소비자는 입술을 붉게 칠하는 립스틱을 사는 것이 아니라\n,\n그 립스틱이 담고 있는 브랜드 철학을 자신의 라이프스타일에 입히고 있는 셈이다\n.\n피부 관리 시작한 러시아 남성들\n, K-Pop\n도 영향\n건강한 피부는 젊음과 성공의 상징이라는 인식이 남성들에게 확산되고 있다\n.\n‘\nInfoline\n’\n에 따르면\n’\n25\n년 남성 화장품 판매는 전년 대비\n20%\n증가했는데\n,\n이는 여성 제품 증가율\n(13%)\n보다 높은 수치다\n.\n‘\nCommerce\n’\n에 따르면,\n’\n25\n년 남성 화장품 부문에서 소매체인\n‘\nWildberries\n’\n는\n247\n억 루블\n(\n약\n2억9600만 달러\n)\n,\n‘\nOzon\n’\n은\n145\n억 루블\n(약\n1억7400만 달러\n)\n의 매출액을 기록했다\n.\n‘\nCollagene 3D Medical\n’\n사의 전무이사'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='약\n2억9600만 달러\n)\n,\n‘\nOzon\n’\n은\n145\n억 루블\n(약\n1억7400만 달러\n)\n의 매출액을 기록했다\n.\n‘\nCollagene 3D Medical\n’\n사의 전무이사\n‘\n나제즈다 볼코바\n’\n는 무역관과의 인터뷰에서\n“최근\n러시아 남성들은\n셰\n이빙\xa0로션 뿐만 아니라\n,\n보습제\n,\n세럼\n,\n자외선차단제\n,\n화장품을 구매한다\n.”\n고\xa0언급했다\n. 한편\n뷰티체인\n‘\nIl De Bote\n’\n의 메이크업 아티스트인\n‘\n아나스타샤 율리나\n’\n는\n“\n남성들에게 안티 에이징 화장품이 인기\n”\n라면서\n“\n남성 화장품의 인기에\nK-Pop\n이 미친 영향을 무시할 수 없다.\n”\n고 밝혔다.\n<맥주 캔 디자인의 남성용 샤워젤 제품\n(\n좌\n), Wildberries\n남성용 화장품\xa0검색 결과\n(\n우\n)>\n[자료: Wildberries\n]\n뷰티 전문 리테일러들의 서비스 전문화와\nAI\xa0적용 확대\n화장품\xa0소매점들의 서비스는 더욱 전문화되고 있다\n.\n다양한 제품과 서비스에 대해\xa0충분한 사전 교육을 받은 종업원들이 먼저 고객에게 다가가 피부 컨디션을\xa0묻고 화장품을 추천한다\n.\n소비자들의 반응과 문의를 기다리던 과거와 달라진 모습이다\n.\n매\n장\n인\n테\n리\n어\n디\n자\n인도\n트\n렌\n드\n에'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n소비자들의 반응과 문의를 기다리던 과거와 달라진 모습이다\n.\n매\n장\n인\n테\n리\n어\n디\n자\n인도\n트\n렌\n드\n에\n맞\n게\n수시로\n바\n꾸\n고\n,\n브\n랜\n드\n와\n제\n품\n도\n소\n비\n자\n들\n이\n보\n기\n편\n하\n게\n분류해\xa0배치하고 있다.\xa0감\n각\n적인 디자인의\xa0각종\xa0특별 판촉\xa0공간, 체험존도\xa0운영한다.\n<Golden Apple 노보시비르스크 지점 내 제품 체험존>\n[자료: Golden Apple\n]\nAI 활용도 늘고 있다.\xa0AI를 통해\n피부 진단과 제품 선택을 지원하는\n‘BeautyScan’\n서비스는 소매체인\n‘Magnit Cosmetic’\n의\n2500\n개 매장에서 제공되고 있다\n.\n서비스 도입 이후 사용자들의 평균 구매 금액이\n29%\n증가했으며 매장 방문 빈도도 운영 전 대조군 대비\n35%\n증가한 것으로 나타났다\n.\n러시아 화장품 제조사이자 피부진단 기업인\n‘GELTEK’\n는 얼굴 이미지를 통해 피부 문제를 진단하는 러시아 최초의\nAI\n서비스\n‘Skin Assistant’\n를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>\n[자료: Skin Assiatant\n]\nK-Beauty 트렌드\xa0지속\n‘\nS&P Global\n’\n에 따르면,\n‘25\n년 러시아의 화장품\n(HS Code 3404)\n수입 규모는 약\n12\n억 달러로 전년 대비\n7.8%\n성장했다\n.\n이 중 한국산 화장품 수입액은\n3\n억6000만\n달러로 전년대비\n12%\n이상 성장\n,\n러시아 내\n1\n위 수입국 지위를 유지하고 있다\n. 2\n위인 프랑스\n(\n1\n억8000만\n달러\n)\n와는 약\n2\n배의 격차이다\n.\n’\n25\n년\n4\n월\n,\n러시아 정부는 비우호국산 화장품 및 향수에 대한 고율 관세 부과 대상에서 한국을 전격 제외했다\n.\n이에 따라\xa0과거에 부과되던\n35%\n의 고율 관세 대신\n,\n한국산 제품은\n6.5%\n의 표준 관세율을 적용받게 됐다\n.\n대상 품목은 향\n수\n,\n화장수\n,\n색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content=',\n색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액\n(HS Code 3304:\n미용\n·\n메이크업용 및 기초화장품류\n)>\n(단위: US$ 천, %)\n순번\n국가\n수입액\n증가율\n2025/2024\n2023\n2024\n2025\n총액\n1,103,557\n1,103,011\n1,189,001\n7.80\n1\n대한민국\n316,157\n322,347\n361,229\n12.06\n2\n프랑스\n130,437\n148,342\n180,498\n21.68\n3\n중국\n122,882\n113,498\n155,169\n36.71\n4\n독일\n72,753\n85,998\n91,707\n6.64\n5\n폴란드\n138,545\n110,257\n85,555\n-22.40\n6\n이탈리아\n37,126\n83,896\n75,595\n-9.89\n7\n카자흐스탄\n25,240\n44,150\n62,459\n41.47\n8\n이스라엘\n40,646\n34,642\n33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]\n<화장품\xa0체인점 Golden\xa0Apple내\xa0한국화장품 섹션 중 일부>\n[자료:\nKOTRA\n노보시비르스크\n무역관 자체 촬영]\n시사점\n경제제재 이후 해외 브랜드 철수\n,\n병행수입\n,\n물류 상황 변화가\xa0겹치면서 러시아의 기존 수입 브랜드 유통 구조가 변화해왔다\n.\n이 과정에서 기존 소매업체들은 단순 판매보다 새로운 브랜드 포트폴리오 확보와 자체 대응이 중요해졌다\n.\n러시아 로컬 브랜드는 수요 공백을 메우며 빠르게 성장했고\n,\n일부는 생산까지 확대했다\n.\n러시아 시장에서는\n“\n매장에 올리는 것\n”\n보다\n“\n소비자의 욕실과 화장대에 들어가는 것\n”\n이 중요해졌다는 표현이 나올 정도로\n,\n브랜드 경쟁이 치열해졌다\n.\n이는 단순 유통보다 브랜드 소유와 제품 기획 역량이 중요해졌다는 의미이다\n.\n전시 고물가 추세가 지속되는 상황에서,\n우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='전시 고물가 추세가 지속되는 상황에서,\n우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다\n.\xa0독특한 성분과\xa0입증된\xa0효과를 갖춘 제품을\xa0지속적으로\xa0제안하고,\n인증, 물류, 마케팅\xa0등에서 체계적이고 신속한 대응 체계를 갖추는 한편, 브랜드가 가진 철학을 정직하고 일관성 있게 전달할 필요가 있다. 제품의 수출과 함께 K-Beauty의 프리미엄\xa0이미지를\xa0구축해 나갈\xa0시기이다.\n러시아 제조사\n‧\n뷰티전문체인과의 다각적인 파트너\n십\n구축\n,\nOEM\n‧\nODM\n협력\n,\n대형 디스트리뷰터 뿐만 아니라 지방의 유력 중견 바이어들과의\xa0네트워크\xa0확대\xa0등을 검토하고\n,\xa0홈뷰티,\n약국용 화장품\n,\n친환경\n,\n남성용\xa0제품 등\xa0성장 분야에도 관심을 가질 필요가 있다\n. 러시아\xa0수출을\xa0처음 추진하는\xa0기업들은 InterCharm(\nhttps://en.intercharm.ru/\n) 등\n전문\n전시\n회에\n참가하는 것도\n시장\xa0파악과\xa0관심\xa0바이어\xa0발굴에 효과적인\xa0방안이 될 수 있다.\n자료\n: Kommersant 등\nKOTRA\n노보시비르스크 무역관 자료 종합'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='요약\n도미니카공화국은 2025년 12월 법률 제98-25호 시행을 통해 플라스틱·발포(폼) 제품의 수입 및 유통 규제를 강화하였다. 동 법은 생분해성 인증 의무화와 생산자책임재활용제도(EPR) 확대를 주요 내용으로 하며, 발포폴리스티렌(EPS) 소재의 빨대·식기류·뚜껑·컵·용기 등은 적정한 환경 인증 없이는 수입이 금지된다. (법령 명칭 : 통합 고형폐기물 관리 및 공동처리법 개정안 (법률 제98-25호) / 현지어 명칭 : Ley Núm. 98-25 que modifica la Ley General de Gestión Integral y Coprocesamiento de Residuos Sólidos)\n2026\n년 2월 15일 동 법 발효 이후 관련 품목 통관 단계에서 도미니카공화국 관세청(DGA)이 인증 여부를 확인하고 있으며, 인증 서류 미비 시 통관 지연 또는 반송 사례가 발생하고 있는 것으로 파악된다.'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='이번 규제는 환경정책의 변화에 그치지 않고 도미니카공화국 수입시장의 거래 조건에도 영향을 주고 있다. 한국 수출기업이 현지 바이어에게 직접 납품하는 구조라면 부담금이나 EPR 의무의 직접 대상은 아닐 수 있으나, 현지 수입업체의 규제 부담이 인증 자료 요청, 포장재 변경 요구, 가격 재협상 등의 형태로 공급업체에 전가될 수 있다.\n한편 기업 부담금 수준을 두고 현지 상공계와 정부·국회 간 협의가 진행 중이다(2026년 4월 현재). 부담금 체계는 변동 가능성이 있으나, 수입 금지 및 인증 의무화 조항은 그대로 적용되고 있어 대 도미니카공화국 수출기업 그리고 현지에 진출한 기업들의 지속적인 모니터링과 대응이 요구된다.\n개요'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='개요\n법률 제98-25호는 기존 통합 고형폐기물 관리법(제225-20호)을 개정한 것으로, 2025년 12월 15일 공포되었다. 기존 법이 폐기물 관리 일반 기준에 초점을 맞춘 것과 달리, 개정법은 소재(material) 단위로 규제 대상을 설정한다. 특정 산업에 한정되지 않고, 발포 또는 비생분해성 플라스틱 소재를 사용하는 모든 제품이 규제 검토 대상에 포함된다. 이에 따라 완제품 수출기업뿐 아니라 현지 제조업체에 포장재나 부자재를 공급하는 기업도 영향권에 놓일 수 있다.\n규제 대상 주요 품목은 다음과 같다.\n폼(발포폴리스티렌, EPS) 소재 : 빨대·포크 나이프·숟가락·뚜껑·컵 등 (2026.02.15부터 즉시 수입 금지, 인증 없는 경우)\n일반 플라스틱 소재 : 빨대·포크 나이프·숟가락 (법 시행 후 12개월 이내 유통 금지, 인증 없는 경우)\n일회용 비닐봉투 : 법 시행 후 12개월 이내 무상 제공 금지\n규제 예외 품목으로는 의료·병원·실험실용 플라스틱 용기, 도로공사 및 건설용 플라스틱이 인정된다.\n또한 경첩형 뚜껑이 일체형으로 부착된 폼 식품 용기(예: 힌지 뚜껑 도시락 용기)는 유통 금지 조항에서 예외로 명시되어 있다.'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='또한 경첩형 뚜껑이 일체형으로 부착된 폼 식품 용기(예: 힌지 뚜껑 도시락 용기)는 유통 금지 조항에서 예외로 명시되어 있다.\n다만 예외 인정을 위해서는 해당 사유를 설명하는 서류 준비가 필요하다.\n생분해성 인증 기준은 시험기관의 검증을 통해 1년 내 최소 20%, 또는 최대 5년 내 9\n0% 이상의 분해율을 충족해야 한다\n.\n다만\xa0도미니카공화국품질원(INDOCAL)이\xa0세부\xa0기술\xa0기준\xa0및\xa0인증\xa0검증\xa0절차는\xa0아직\xa0마련\xa0중에\xa0있어,\xa0통관\xa0현장에서는 기준 적용 방식 등 관련하여 다소간의 혼선이 빚어질 수 있다. 현재\n국제\n규격에\n따른\n해외\n인증이\xa0다소\n광범위하게\n인정되고\xa0있으나,\xa0추후\xa0기준과\xa0절차\xa0정립\xa0후에는\xa0항목별로\xa0정확한\xa0준용이\xa0필요할\xa0것으로\xa0보인다.\n동\n법이 권장하는 대체 소재로는 종이, 재활용·생분해성 판지, 사탕수수\xa0부산\n물\n(bagasse), 대나무, 식물성 섬유, 퇴비화 가능 소재(compostable), 인증된 생분해성 소재, 재사용 가능 용기 등이 있다.\n집행\n기관\n관련,\n관세청(DGA)이\n통관 시\n인증\n서류를'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='집행\n기관\n관련,\n관세청(DGA)이\n통관 시\n인증\n서류를\n확인하고, 도미니카공화국품질원(INDOCAL)이 기술 검증을 지원하며, 환경부(Ministerio de Medio Ambiente y Recursos Naturales)가 제\n도\n전반의\n준수를\n감독한다.\n제도 시행 및 단계별 이행 일정\n동 법은 수입 절차와 국내 시장 운영 전반에 영향을 미치는 단계적 시행 조치를 규정하고 있다.\n<법령 시행 관련 일정>\n구분\n시행일\n주요 내용\n법률 제98-25호 시행\n2025.12.15\n개정된 폐기물관리 체계 시행\n폼 제품 수입금지\n2026.02.15\n빨대·식기·뚜껑·컵 등 미인증폼 제품 수입 금지\n폐기물 배출자등록\n2026.06.15\n환경부 대상사업자 등록 의무화\n일반 플라스틱식기·빨대 유통 금지\n2026.12.15\n미인증 플라스틱빨대·포크·숟가락·나이프유통 금지\n생산자책임재활용제도(Extended Produce Responsibility) 관리계획 제출\n2026.12.15\n폐기물 관리계획제출 의무\n무상 비닐봉투제공 금지\n2026.12.15\n일회용 비닐봉투무상 제공 금지\n발포 제품 대체전환\n2027.12.15\n친환경 대체소재로 전환\n지자체 분리배출프로그램'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='무상 비닐봉투제공 금지\n2026.12.15\n일회용 비닐봉투무상 제공 금지\n발포 제품 대체전환\n2027.12.15\n친환경 대체소재로 전환\n지자체 분리배출프로그램\n2028.12.15\n지방정부 선택적수거 프로그램 확대\n실무적으로는 법률상 일정과 실제 통관·인증 운용 사이에 차이가 발생할 수 있다. INDOCAL의 세부 기술 기준이 확정되는 과정에서 혼선이 발생할 가능성이 있으므로, 현지 바이어가 실제로 어떤 서류를 요구받고 있는지를 확인하는 것이 단순히 법률 시행일을 확인하는 것보다 실질적인 대응에 도움이 될 것으로 사료된다.\n생산자책임재활용제도(EPR) 및 기업 부담금 관련 현황'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='생산자책임재활용제도(EPR) 및 기업 부담금 관련 현황\n강화된 제도 하에서, 도미니카공화국 시장에 규제 대상 소재를 유통하는 기업은 수거, 재활용 등 사후 폐기물 관리에 대한 책임을 부담한다. 비닐봉투·플라스틱병 생산자는 법 시행 후 12개월 이내에 폐기물 회수·처리·처분 프로그램에 참여해야 한다. 한국에서 도미니카공화국으로 제품을 수출하는 기업이 곧바로 현지 부담금 납부 대상이 되는 구조는 아닌 것으로 파악된다. 다만 현지 수입업체, 유통업체, 제조업체가 관련 의무와 부담금을 부담하게 되면, 해당 비용이 인증 자료 요청, 발주 축소, 포장재 변경 요구, 가격 재협상 등의 형태로 한국 공급업체에 전가될 수 있다.'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='동 법령을 통해 정부는 기업의 연간 매출액을 기준으로 산정되는 특별부담금(Contribución Especial) 제도를 도입하였다. 이 부담금은 EPR 의무 대상인 생산자·수입자·유통업자에 한정되지 않으며, 도미니카공화국 내에 등록된 모든 공·사법인(todas las personas jurídicas, públicas y privadas) 에 적용된다. 즉, 플라스틱 제품을 직접 생산하거나 수입하지 않더라도, 사업 운영 과정에서 폐기물을 발생시키는 법인이라면 납부 의무를 지게 된다. 국세청(DGII)이 안내한 바에 따르면 부담금은 연간 매출액 구간에 따라 RD$3,000에서 RD$675,000(약 50~11,250달러) 수준으로 규정되어 있으며, 수익 발생 여부와 관계없이 의무 납부 구조로 설계되어 있다. 이에 대해 도미니카공화국 산업협회(AIRD), 자유무역지대협회(Adozona), 상인연합회 등 주요 경제단체는 매출액 기준 부과 방식의 형평성 문제를 지적하고 있다. 매출이 유사하더라도 실제 폐기물 배출량은 업종에 따라 크게 다를 수 있어, 현행 구조가 조세 비례 원칙에 반한다는 것이 업계의 주된 주장이다.'),

In [34]:
from pathlib import Path

from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_classic.storage import LocalFileStore
from langchain_classic.embeddings.cache import CacheBackedEmbeddings

# 5. 임베딩 캐시 폴더 생성
Path("./data/embeddings").mkdir(parents=True, exist_ok=True)

embedder = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

cache_dir = LocalFileStore("./data/embeddings/kotra_news_body_test")

cache_embedder = CacheBackedEmbeddings.from_bytes_store(
    embedder,
    cache_dir,
    namespace="text-embedding-3-small"
)

In [35]:
# 6. FAISS 벡터스토어 생성
vectorstore = FAISS.from_documents(split_docs, cache_embedder)

# 7. Retriever 생성
retriever = vectorstore.as_retriever(
    search_kwargs={"k": 5}
)

In [41]:
# 8. 검색 테스트
query = "러시아 화장품 시장 전망"

results = retriever.invoke(query)
results

[Document(id='160dba9e-5e49-47a0-a60a-c70bc1440b88', metadata={'row_id': 2, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240931', 'keywords': '#러시아, #식품, #외식, #식당, #호텔, #레스토랑, #Horeca, #전시회, #패스트푸드, #스트릿푸드, #커피, #식품가공기계, #주방, #푸드'}, page_content='앞서 언급된 바와 같이 외국산\n전문\xa0식품가공 및 주방\xa0설비에 대한 수요도 존재한다. 실제로 한국의 대러시아 식품가공기계 수출이 2024년 53.7%, 2025년 47.6%\xa0증가했으며, 식품포장기계도 2025년 수출액이 10.6% 늘었다. (MTI 4단위 기준)\n호텔 부문에서는 비용 절감과 서비스 표준화가 이뤄지며 디스펜서형\xa0어메니티 수요가 확대되고 있다. 동시에 고급 호텔을 중심으로 프리미엄 일회용 제품\xa0수요도 유지되고 있다. 또한,\n최근\n가족 단위 국내 관광이 늘면서 아동용 호텔 화장품이 틈새 품목으로 부상했다.\n전반적으로 러시아 HoReCa 시장은 품질을 유지하면서도 운영 효율성과 비용 절감을 중시하는 방향으로 변화하고 있다. 특히 소스류, 조미 원료, 호텔 소모품 등 B2B 분야에서 진출 기회가 열리고 있다. 부가가치가 높고 품질이 안정적이며, 수요에 맞게 공급 방식과 구성을 조정할 수 있는 제품의 시장성이 클 것으로 보인다.\n자료:\nHORECA EXPO\n공식 홈페이지, RBC, Kommersant, Forbes, METRO,\nKOTRA\n모스크바무역관 등'),
 Document(id='91636aeb-b06e-48c5-9134-82657e02c1ef', metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]\n<화장품\xa0체인점 Golden\xa0Apple내\xa0한국화장품 섹션 중 일부>\n[자료:\nKOTRA\n노보시비르스크\n무역관 자체 촬영]\n시사점\n경제제재 이후 해외 브랜드 철수\n,\n병행수입\n,\n물류 상황 변화가\xa0겹치면서 러시아의 기존 수입 브랜드 유통 구조가 변화해왔다\n.\n이 과정에서 기존 소매업체들은 단순 판매보다 새로운 브랜드 포트폴리오 확보와 자체 대응이 중요해졌다\n.\n러시아 로컬 브랜드는 수요 공백을 메우며 빠르게 성장했고\n,\n일부는 생산까지 확대했다\n.\n러시아 시장에서는\n“\n매장에 올리는 것\n”\n보다\n“\n소비자의 욕실과 화장대에 들어가는 것\n”\n이 중요해졌다는 표현이 나올 정도로\n,\n브랜드 경쟁이 치열해졌다\n.\n이는 단순 유통보다 브랜드 소유와 제품 기획 역량이 중요해졌다는 의미이다\n.\n전시 고물가 추세가 지속되는 상황에서,\n우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다'),
 Document(id='6e351cec-b879-4390-b52c-8d704239a68a', metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모는\n1\n조2000억\n루블\n(\n약\n144\n억 달러\n)\n로 전년 대비\n7%-8%\n증가했다\n. 반면\n판매되는 화장품\xa0수량은 감소세로\n, ‘Nilson’\n에 따르면 스킨케어 화장품 판매량은\n1\n년 만에\n13.3%, ‘\n헤어케어\n’\n는\n5.3%, ‘\n바디케어\n’\n는\n4.1%\n줄었다\n.\n시장 규모가 커졌음에도 판매량이 감소한\xa0주요 원인으로\xa0화장품\xa0가격의\xa0증가가 꼽힌다.\n<연도별 러시아 화장품 판매수량\n및 증가율>\n(단위: 십\n억 개\n)\n[자료\n: Businesstat.ru]\n오프라인 판매는 감소하는 반면\xa0온라인\xa0마켓플레이스에서의\xa0판매가\xa0증가하고 있다\n. ’25\n년 온라인\xa0소매기업\n‘Wildberries’\n의 스킨케어 화장품 매출은\xa0전년 대비\n28%,\n색조 화장품 매출은\n20%\n증가했다\n.\n온라인 소매점들은 프리미엄\n,\n친환경\n,\n아시아 브랜드 등 다양한 카테고리의 메뉴를 운영하며 소비자들을 유입시키고 있다\n.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.'),
 Document(id='35864811-4e03-490f-938f-4de0848bad84', metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>\n[자료: Skin Assiatant\n]\nK-Beauty 트렌드\xa0지속\n‘\nS&P Global\n’\n에 따르면,\n‘25\n년 러시아의 화장품\n(HS Code 3404)\n수입 규모는 약\n12\n억 달러로 전년 대비\n7.8%\n성장했다\n.\n이 중 한국산 화장품 수입액은\n3\n억6000만\n달러로 전년대비\n12%\n이상 성장\n,\n러시아 내\n1\n위 수입국 지위를 유지하고 있다\n. 2\n위인 프랑스\n(\n1\n억8000만\n달러\n)\n와는 약\n2\n배의 격차이다\n.\n’\n25\n년\n4\n월\n,\n러시아 정부는 비우호국산 화장품 및 향수에 대한 고율 관세 부과 대상에서 한국을 전격 제외했다\n.\n이에 따라\xa0과거에 부과되던\n35%\n의 고율 관세 대신\n,\n한국산 제품은\n6.5%\n의 표준 관세율을 적용받게 됐다\n.\n대상 품목은 향\n수\n,\n화장수\n,\n색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액'),
 Document(id='f1e9d29f-a573-4c73-8555-2e8ede2179be', metadata={'row_id': 2, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240931', 'keywords': '#러시아, #식품, #외식, #식당, #호텔, #레스토랑, #Horeca, #전시회, #패스트푸드, #스트릿푸드, #커피, #식품가공기계, #주방, #푸드'}, page_content='Q4.\n러시아 외식 프랜차이즈 시장에 진출할 때 유의사항은 무엇인가요?\nA4\n.\n해외 제조사가 러시아 레스토랑 시장에 들어오려면 현지 유통업체와 협력 구조를 만드는 것이 중요합니다. 저희는 인증된 현지 유통업체와 함께 일하며 중앙에서 공급을 관리하고 있습니다. 해외 공급업체와 직접 거래하는 경우는 많지 않고, 유통망을 통해 제품을 들여오는 방식이 일반적입니다. 공급이 안정적으로 유지되는지, 레스토랑 운영 방식에 맞게 제품을 조정할 수 있는지, 거래 조건이 경쟁력 있는지가 중요합니다.\n시사점\n러시아 HoReCa 시장에서 한국 제품에 대한 관심은 김치, 김, 라면 등 전통적인 품목을 넘어 업소용 수요에 맞춘 제품으로 넓어지고 있다. 특히 성장세가 뚜렷한 분야는 소스와 고부가 식재료다. 프리미엄 아시아풍 소스, 농축 조미 원료처럼 외식업체가 메뉴 개발과 조리 효율화를 위해 활용할 수 있는 제품에 대한 수요가 늘고 있다.\n앞서 언급된 바와 같이 외국산')]

# Qwen3-Embedding-0.6B-MLX-4bit 임베딩

In [20]:
# 1. CSV 읽고 첫 10개 본문 가져오기

import pandas as pd

df = pd.read_csv("data/kotra_news_body.csv", encoding="utf-8-sig")
df.columns = df.columns.str.replace("\ufeff", "", regex=False).str.strip()

df = df[
    df["본문"].notna() &
    (df["본문"].astype(str).str.strip() != "")
].reset_index(drop=True)

df_sample = df.iloc[:10]
print(df_sample.shape)
df_sample.head()

/var/folders/wx/rj6wt5wn1yl8195jd9gqn5jc0000gn/T/ipykernel_3550/4108863917.py:5: DtypeWarning: Columns (0: 일자리구분명) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/kotra_news_body.csv", encoding="utf-8-sig")

(10, 20)

,품목명한글,뉴스제목,게시물 URL,일자리구분명,HS코드명,저작권 정책,품목명영문,지역,파일링크,산업분류,산업분류코드목록,무역관정보,뉴스게시일자,게시글일련번호,뉴스작성자명,정보분류(메뉴ID),정보분류(메뉴명),국가,키워드,본문
0,"미용이나 메이크업용 제품류와 기초화장용 제품류[의약품은 제외하며, 선스크린(suns...",고물가와 경쟁 속 변화하는 러시아 뷰티 시장,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,3304,4유형,Beauty or make-up preparations and preparation...,유럽,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,생활소비재,I001198,노보시비르스크무역관,2026-05-04,240938,김하민,243,트렌드,러시아연방,"#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출",‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모...
1,NaN,"도미니카공화국, 플라스틱 제품류 수입, 유통 기업 대상 환경 규제 강화",https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,중남미,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,"화학,환경","I001212,I001203",산토도밍고무역관,2026-05-04,241022,Adriana Jimenez,242,경제·무역,도미니카공화국,"#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제",요약\n도미니카공화국은 2025년 12월 법률 제98-25호 시행을 통해 플라스틱·...
2,NaN,HORECA EXPO에서 살펴보는 러시아 외식산업 트렌드와 유망 분야,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,유럽,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,"농림수산식품,섬유/패션,생활소비재,유통/물류,관광/교육/서비스,산업일반","I001193,I001197,I001198,I001208,I001210,I001307",모스크바무역관,2026-05-04,240931,정의한,245,현장·인터뷰,러시아연방,"#러시아, #식품, #외식, #식당, #호텔, #레스토랑, #Horeca, #전시회...",<HORECA Expo 2026\n전시회\n개요\n>\n전시회명\nHORECA EX...
3,"미용이나 메이크업용 제품류와 기초화장용 제품류[의약품은 제외하며, 선스크린(suns...",[해외시장뉴스플러스] &lsquo;K-Lifestyle in Chennai&rsqu...,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,3304,4유형,Beauty or make-up preparations and preparation...,아시아,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,생활소비재,I001198,첸나이무역관,2026-05-04,240981,윤병은,243,트렌드,인도,"#뷰티, #화장품, #인도, #전자상거래, #온라인, #K-뷰티, #인플루언서, #인터뷰",인도\nK-\n뷰티 시장 확대\n인도 화장품 시장이 빠르게 커지고 있다. 시장조사 ...
4,NaN,2026 케냐 국제 투자 컨퍼런스를 통해 살펴본 케냐 투자유치 동향 및 전망,https://dream.kotra.or.kr/user/extra/kotranews...,NaN,NaN,4유형,NaN,아프리카,https://dream.kotra.or.kr/ajaxa/fileCpnt/fileD...,산업일반,I001307,나이로비무역관,2026-05-04,241000,신정렬,322,투자진출,케냐,"#케냐, #투자, #컨퍼런스","최근 케냐는 '제조업 기반의 경제 성장'이라는 확고한 목표 아래, 파격적인 투자 환..."

In [21]:
# 2. LangChain Document 만들기
from langchain_core.documents import Document

docs = []

for idx, row in df_sample.iterrows():
    doc = Document(
        page_content=row["본문"],
        metadata={
            "row_id": idx,
            "url": row.get("게시물 URL", ""),
            "keywords": row.get("키워드", "")
        }
    )
    docs.append(doc)

print("문서 개수:", len(docs))
docs[0]

문서 개수: 10

Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모는\n1\n조2000억\n루블\n(\n약\n144\n억 달러\n)\n로 전년 대비\n7%-8%\n증가했다\n. 반면\n판매되는 화장품\xa0수량은 감소세로\n, ‘Nilson’\n에 따르면 스킨케어 화장품 판매량은\n1\n년 만에\n13.3%, ‘\n헤어케어\n’\n는\n5.3%, ‘\n바디케어\n’\n는\n4.1%\n줄었다\n.\n시장 규모가 커졌음에도 판매량이 감소한\xa0주요 원인으로\xa0화장품\xa0가격의\xa0증가가 꼽힌다.\n<연도별 러시아 화장품 판매수량\n및 증가율>\n(단위: 십\n억 개\n)\n[자료\n: Businesstat.ru]\n오프라인 판매는 감소하는 반면\xa0온라인\xa0마켓플레이스에서의\xa0판매가\xa0증가하고 있다\n. ’25\n년 온라인\xa0소매기업\n‘Wildberries’\n의 스킨케어 화장품 매출은\xa0전년 대비\n28%,\n색조 화장품 매출은\n20%\n증가했다\n.\n온라인 소매점들은 프리미엄\n,\n친환경\n,\n아시아 브랜드 등 다양한 카테고리의 메뉴를 운영하며 소비자들을 유입시키고 있다\n.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.\n소비자의\xa0구매력\xa0약화는\xa0멀티기능성\n,\n가성비\n,\n현지\xa0브랜드\xa0선호를\xa0키웠고\n,\n이는\xa0제조와\xa0판매\xa0모두에서\xa0더\xa0촘촘한\xa0가치사슬\xa0대응을\xa0요구했다\n.\n소매 기업들이 화장품을 직접 제조해 판매하고\n제조사들이 자체 판매망을 구축해 제품을 판매하는 등\n,\n전통적인 기업 형태 구분이 모호해지고\n,\n가치 사슬이\xa0복잡해지는 양상이다\n.\n리테일러들이\nOEM\n을 통해 자체 브랜드 제품을 생산해 판매하고\n,\n별도 유통사들을 통해서만 제품을 공급하던 제조사들도 자체 온라인 마켓플레이스를 구축해 판매하고 있다\n.\n식료품 소매체인\n‘VKUSVILL’\n은 자체 브랜드의 미스트\n,\n핸드크림 등 제품을 화장품 전문 소매체인\n‘Letual’\n사이\n트\n를 통해 판매하고 있고\n,\n소비재\n·\n식료품 소매체인\n‘Magnit’\n도 자체 PB\xa0화장품을 화장품 소매체인\n‘\n골든 애플\n’\n온라인 스토어에서\xa0판매하고 있다\n.\n<뷰티체인\nLetual\n사이트에서 판매되는\nVkusvill(\n식품소매점\n)\n브랜드 화장품>\n* 주\n:\n번역기 통해 러시아어를 한국어로 변환\n[자료\n: Letual]\n로컬 브랜드 확산\n물류\n·\n관세\n·\n환율의\xa0급변\xa0상황에서 러시아\xa0브랜드\xa0공급은 지속 확대되고 있다\n.\n러시아\n산업통상부에 따르\n면\n,\n’\n25\n년 향수 및 화장품 시장에서 러시아 제품 점유율은\n68%\n이다\n.\n‘\nBusinessStat\n’\n에 따르면 러시아에서 생산된 스킨케어\n제품 개수는\n‘21\n년\n2\n억9000\n만\n개에서\n‘25\n년\n3\n억7000만\n개로\n26%\n증가했다\n.\n러시아 정부는\n’\n27\n년\n3\n월부터 모든 소비재 소매 체인점에서 러시아산 비식품 제품을 의무적으로 진열하게 하는 법안인 일명\n"\n러시아 제품 진열대\n"\n를 발표했는데 러시아제 화장품\n,\n향수를 우선 대상 제품으로 검토하고 있다\n.\n<\n러시아 상위\n10\n위\n화장품 제조사\n>\n(단위: 백만 루블)\n연번\n회사명\n개요\n지역\n홈페이지\n매출액\xa0(\'25년 기준)\n1\nFaberlic JSC\n화장품, 의류, 액세서리, 신발 및 기타 품목 제조\n모스크바\nfaberlic.com/ru/ru\n35,668.4\n2\nNTS Gradient LLC\n색조 및 스킨케어 화장품 독점 유통\n모스크바\nwww.gradient.ru\n29,739.88\n3\nUni\nc\no\nsmetic\nLLC\n헤어케어 및 염모제 생산\n상트페테르부르크\nestel.pro\n17,506.67\n4\nArnest JSC\n데오도란트, 안면·전신용 화장품, 식품 등 생산\n스타브로폴 지방 네비노미스크\nwww.arnest.ru\n17,455.63\n5\nZettek LLC\n물티슈 및 건티\n슈 생산\n칼루가 주\nzettek.ru\n9,914.62\n6\nSibair JSC\n스프레이 및 데오도란트 생산\n노보시비르스크\nwww.sibiar.ru\n7,654.56\n7\nGrand AV LLC\n냅킨\n및 마스크 생산\n툴라 주\nwww.grand-av.ru\n6,190.97\n8\nOrganic Pharmaceuticals LLC\n치약 제조\n노브고로드 주\nwww.splat.ru\n5,672.87\n9\nAct LLC\n안면, 전신 및 모발용 케어 화장품 제조\n모스크바\ntheact.ru\n5,402.55\n10\nBiopharmrus LLC\n화장품, 식품 첨가물 및 의\n료용품 OEM 생산\n모스크바주 포돌스크\nbiofarmrus.com\n5,323.84\n* 주: 일부 치약, 물티슈 등 생활소\n비재 제조 포함\n[자료: Gl\nobus]\n홈뷰티\n(a\nt\n‑\nhome beauty)\n확산\n,\n코스메슈티컬\n(\ncosmeceuticals)\n시장 성장\n러시아 뷰티 서비스 가격은 빠르게\xa0인상되고 있다\n. ‘Informer’\n에 따르면,\n’25\n년 헤어\n,\n스파\n,\n숍 등 뷰티 서비스 비용은 전년 대비\n10%-14%\n증가했다\n.\n부동산 임대료 증가\n,\n숙련 인력 급여 인상\n,\n영세업체\nVAT\n면제 한도 변경 등이 가격 인상의 주요 원인으로 꼽힌다.\n‘\n뷰티 기업 및 전문가 협회\n’\n회장인\n‘\n랴 소디코바\n’\n는\n“서비스\n가격 인상의 영향으로\n’\n25\n년\n9-12\n월 기간 러시아인들의 각종 뷰티 숍 방문 빈도가 전년 대비\n20-30%\n감소했다\n.”\n고 말한다\n.\n소비자들은 값비싼 미용 장비를 이용하거나 필러 등을 주입하는 대신 갈바닉\n, LED\n마스크 등 소형 미용 기기를 구입해 집에서 피부를 관리하기 시작했다\n.\n고급 스파 대신 아로마틱 화장품과 스파 용품을 구매해 집에서 목욕을 하는 추세도 나타나고 있다.\n<\n마이크로전류 제품\nMedicube(\n좌\n), LED\n마스크\nL&L SKIN(\n우\n)>\n[자료: Medicube, Ozon]\n노화를 미리 대비하는\n‘\n노화 예방\n’\n에 대한 관심도 높아졌다\n.\n젊은 소비자들 사이에서\xa0자외선 손상\n,\n콜라겐 감소\n,\n표정 주름\n,\n피부 지지대 약화가 주요 관심사로 부상하고 있다.\n‘\n겉만 예뻐 보이는 마사지\n’\n가 아니라 피부 속 림프 순환\n,\n부종 감소\n,\n독소\n·\n노폐물 배출을 돕는 마사지 서비스나 진동 치료가 증가하고 있다\n.\n주사 없이 히알루론산\n,\n비타민 등을 피부에 투입하는 더마드롭\n(Dermadrop),\n콜라겐 등의 생성을 돕는 생체활성화\n(Bioactivation)\n에 대한 관심도 높다\n.\n과학적으로 입증된 효능을 가진 이른 바 약국에서 판매되는 화장품인 코스메슈티컬\n(cosmeceuticals)\n판매량은 최근\n3\n년간 꾸준히 증가하고 있다\n.\n<러시아 연도별/월별 약국화장품 판매량>\n(단위: 십억\n루블\n)\n[자료\n: DSM Group]\n성분표 확인하는 소비자들, 친환경 오가닉 제품 인기\n시장 규모가 크진 않지만 친환경 오가닉 화장품도 견조한 성장을 이어가고 있다\n.\n제품 성분표에서 화학 첨가제 포함 유무를 확인하는 소비자가 늘고\n,\n그린워싱\n(\n위장환경주의\n)\n에 대한 관심도 높아져 국제\n친환경 제품 인증서를 받으려는 기업들도 많아지고 있다\n.\n천연 화장품 수요가 가장 큰 제품군은\n‘\n얼굴 케어\n’\n이며\n,\n황산염 무함유 샴푸\n,\n오일 함유 린스 등\n‘\n헤어 케어\n’\n에 대한 수요도 높다\n.\n립스틱 같은 제품에 천연 원료 함유나 포장 재활용 문구도 많이 나타난다\n.\n러시아 정부는\n"Organic"\n라벨을 도입하는 한편\n,\n’\n25.10\n월에\n‘\n예비 국가 표준\n’\n을 승인\n,\n특정 요건을 충족하는 제품에 한해\n‘\n자연\n’\n,\n‘\n유기농\n’\n,\n‘그린\n’\n등의 단어를 쓸 수 있도록\xa0하는\xa0규제를 준비하기 시작했다\n.\n<동물 테스트 반대 표방 러시아 천연 화장품 브랜드\nMatsesta>\n[자료: Matsesta]\n복고풍의 귀환과 스토리\xa0감성 마케팅\n뷰티 업계는 수년간 이어져 온\n‘\n클린 걸\n(Clean Girl)’\n과\n‘\n미니멀리즘\n’\n에서 벗어나\n,\n과감하고 다채로운\n2000\n년대 감성으로 회귀하고 있다\n.\n계속되는 러-우 사태가 과거에 대한 향수를 자극한 측면이\xa0있다\n.\n단순히 따라 하는 화장이나 꾸안꾸 스타일이 아닌\n,\xa01990\n년대의\xa0섹시함과\n‘\n개성 중심의 뷰티\n’\n가 주목받고 있다\n.\xa0특히\n젊은층에서\n2000\n년대 스타일의 글리터 섀도우\n,\n그라데이션 립 등이 유행이다\n. 최근\xa0러시아\n패션 브랜드\n‘Gloria Jeans’\n는 러시아\nSNS\n인\n‘VK’\n와\n2000\n년\nY2K\n를 주제로 한 콜라보레이션 마케팅을 진행했다\n.\n<\n‘Gloria Jeans’\n와\n‘VK.com’\n콜라보레이션\n>\n[자료: Gloria Jeans]\n기능이나 가격보다\n‘\n브랜드가 전하는 이야기\n’\n에 열광하는 소비자들이\xa0늘고 있다\n.\n단순한 상품 구매를 넘어\n,\n브랜드 철학을 공유하고 정서적인 만족을 얻을 수 있는\n‘\n감성 마케팅\n’\n과\n‘\n스토리텔링\n’\n을 원하는 고객들이 많다\n.\n러시아 기업\n‘Natura Siberica’\n는 러시아 전통 도자기\n‘\n그젤\n(Gzhel)’\n문양을 활용한 디자인을 통해 브랜드에 애국심과 민족적 정체성을 입혔다\n.\n러시아인의 향수와 문화적 자부심을 자극하는 감성 마케팅 사례로 꼽힌다\n.\n‘Erinel’\n사는\n‘\n엘프의 전설\n’\n이라는 독특한 세계관을 브랜드에 녹여냈다\n.\n엘프의 마법 이야기를 모든 제품과 디자인에 담아냈다\n.\n이러한 차별화된 세계관은 강력한 팬덤을 형성하는 원동력이 됐다\n.\n<러시아 전통 디자인을 차용한\nNatura Siberica,\n엘프 스토리를 활용한\n‘Erinel’>\n[자료: Natura Siberica, Erinel\n]\n마케팅 흐름은 이제\n‘\n성능과 효율\n’\n을 강조하던 시대에서\n‘\n공감과 가치\n’\n를 공유하는 시대로 넘어왔다\n.\n소비자는 입술을 붉게 칠하는 립스틱을 사는 것이 아니라\n,\n그 립스틱이 담고 있는 브랜드 철학을 자신의 라이프스타일에 입히고 있는 셈이다\n.\n피부 관리 시작한 러시아 남성들\n, K-Pop\n도 영향\n건강한 피부는 젊음과 성공의 상징이라는 인식이 남성들에게 확산되고 있다\n.\n‘\nInfoline\n’\n에 따르면\n’\n25\n년 남성 화장품 판매는 전년 대비\n20%\n증가했는데\n,\n이는 여성 제품 증가율\n(13%)\n보다 높은 수치다\n.\n‘\nCommerce\n’\n에 따르면,\n’\n25\n년 남성 화장품 부문에서 소매체인\n‘\nWildberries\n’\n는\n247\n억 루블\n(\n약\n2억9600만 달러\n)\n,\n‘\nOzon\n’\n은\n145\n억 루블\n(약\n1억7400만 달러\n)\n의 매출액을 기록했다\n.\n‘\nCollagene 3D Medical\n’\n사의 전무이사\n‘\n나제즈다 볼코바\n’\n는 무역관과의 인터뷰에서\n“최근\n러시아 남성들은\n셰\n이빙\xa0로션 뿐만 아니라\n,\n보습제\n,\n세럼\n,\n자외선차단제\n,\n화장품을 구매한다\n.”\n고\xa0언급했다\n. 한편\n뷰티체인\n‘\nIl De Bote\n’\n의 메이크업 아티스트인\n‘\n아나스타샤 율리나\n’\n는\n“\n남성들에게 안티 에이징 화장품이 인기\n”\n라면서\n“\n남성 화장품의 인기에\nK-Pop\n이 미친 영향을 무시할 수 없다.\n”\n고 밝혔다.\n<맥주 캔 디자인의 남성용 샤워젤 제품\n(\n좌\n), Wildberries\n남성용 화장품\xa0검색 결과\n(\n우\n)>\n[자료: Wildberries\n]\n뷰티 전문 리테일러들의 서비스 전문화와\nAI\xa0적용 확대\n화장품\xa0소매점들의 서비스는 더욱 전문화되고 있다\n.\n다양한 제품과 서비스에 대해\xa0충분한 사전 교육을 받은 종업원들이 먼저 고객에게 다가가 피부 컨디션을\xa0묻고 화장품을 추천한다\n.\n소비자들의 반응과 문의를 기다리던 과거와 달라진 모습이다\n.\n매\n장\n인\n테\n리\n어\n디\n자\n인도\n트\n렌\n드\n에\n맞\n게\n수시로\n바\n꾸\n고\n,\n브\n랜\n드\n와\n제\n품\n도\n소\n비\n자\n들\n이\n보\n기\n편\n하\n게\n분류해\xa0배치하고 있다.\xa0감\n각\n적인 디자인의\xa0각종\xa0특별 판촉\xa0공간, 체험존도\xa0운영한다.\n<Golden Apple 노보시비르스크 지점 내 제품 체험존>\n[자료: Golden Apple\n]\nAI 활용도 늘고 있다.\xa0AI를 통해\n피부 진단과 제품 선택을 지원하는\n‘BeautyScan’\n서비스는 소매체인\n‘Magnit Cosmetic’\n의\n2500\n개 매장에서 제공되고 있다\n.\n서비스 도입 이후 사용자들의 평균 구매 금액이\n29%\n증가했으며 매장 방문 빈도도 운영 전 대조군 대비\n35%\n증가한 것으로 나타났다\n.\n러시아 화장품 제조사이자 피부진단 기업인\n‘GELTEK’\n는 얼굴 이미지를 통해 피부 문제를 진단하는 러시아 최초의\nAI\n서비스\n‘Skin Assistant’\n를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>\n[자료: Skin Assiatant\n]\nK-Beauty 트렌드\xa0지속\n‘\nS&P Global\n’\n에 따르면,\n‘25\n년 러시아의 화장품\n(HS Code 3404)\n수입 규모는 약\n12\n억 달러로 전년 대비\n7.8%\n성장했다\n.\n이 중 한국산 화장품 수입액은\n3\n억6000만\n달러로 전년대비\n12%\n이상 성장\n,\n러시아 내\n1\n위 수입국 지위를 유지하고 있다\n. 2\n위인 프랑스\n(\n1\n억8000만\n달러\n)\n와는 약\n2\n배의 격차이다\n.\n’\n25\n년\n4\n월\n,\n러시아 정부는 비우호국산 화장품 및 향수에 대한 고율 관세 부과 대상에서 한국을 전격 제외했다\n.\n이에 따라\xa0과거에 부과되던\n35%\n의 고율 관세 대신\n,\n한국산 제품은\n6.5%\n의 표준 관세율을 적용받게 됐다\n.\n대상 품목은 향\n수\n,\n화장수\n,\n색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액\n(HS Code 3304:\n미용\n·\n메이크업용 및 기초화장품류\n)>\n(단위: US$ 천, %)\n순번\n국가\n수입액\n증가율\n2025/2024\n2023\n2024\n2025\n총액\n1,103,557\n1,103,011\n1,189,001\n7.80\n1\n대한민국\n316,157\n322,347\n361,229\n12.06\n2\n프랑스\n130,437\n148,342\n180,498\n21.68\n3\n중국\n122,882\n113,498\n155,169\n36.71\n4\n독일\n72,753\n85,998\n91,707\n6.64\n5\n폴란드\n138,545\n110,257\n85,555\n-22.40\n6\n이탈리아\n37,126\n83,896\n75,595\n-9.89\n7\n카자흐스탄\n25,240\n44,150\n62,459\n41.47\n8\n이스라엘\n40,646\n34,642\n33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]\n<화장품\xa0체인점 Golden\xa0Apple내\xa0한국화장품 섹션 중 일부>\n[자료:\nKOTRA\n노보시비르스크\n무역관 자체 촬영]\n시사점\n경제제재 이후 해외 브랜드 철수\n,\n병행수입\n,\n물류 상황 변화가\xa0겹치면서 러시아의 기존 수입 브랜드 유통 구조가 변화해왔다\n.\n이 과정에서 기존 소매업체들은 단순 판매보다 새로운 브랜드 포트폴리오 확보와 자체 대응이 중요해졌다\n.\n러시아 로컬 브랜드는 수요 공백을 메우며 빠르게 성장했고\n,\n일부는 생산까지 확대했다\n.\n러시아 시장에서는\n“\n매장에 올리는 것\n”\n보다\n“\n소비자의 욕실과 화장대에 들어가는 것\n”\n이 중요해졌다는 표현이 나올 정도로\n,\n브랜드 경쟁이 치열해졌다\n.\n이는 단순 유통보다 브랜드 소유와 제품 기획 역량이 중요해졌다는 의미이다\n.\n전시 고물가 추세가 지속되는 상황에서,\n우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다\n.\xa0독특한 성분과\xa0입증된\xa0효과를 갖춘 제품을\xa0지속적으로\xa0제안하고,\n인증, 물류, 마케팅\xa0등에서 체계적이고 신속한 대응 체계를 갖추는 한편, 브랜드가 가진 철학을 정직하고 일관성 있게 전달할 필요가 있다. 제품의 수출과 함께 K-Beauty의 프리미엄\xa0이미지를\xa0구축해 나갈\xa0시기이다.\n러시아 제조사\n‧\n뷰티전문체인과의 다각적인 파트너\n십\n구축\n,\nOEM\n‧\nODM\n협력\n,\n대형 디스트리뷰터 뿐만 아니라 지방의 유력 중견 바이어들과의\xa0네트워크\xa0확대\xa0등을 검토하고\n,\xa0홈뷰티,\n약국용 화장품\n,\n친환경\n,\n남성용\xa0제품 등\xa0성장 분야에도 관심을 가질 필요가 있다\n. 러시아\xa0수출을\xa0처음 추진하는\xa0기업들은 InterCharm(\nhttps://en.intercharm.ru/\n) 등\n전문\n전시\n회에\n참가하는 것도\n시장\xa0파악과\xa0관심\xa0바이어\xa0발굴에 효과적인\xa0방안이 될 수 있다.\n자료\n: Kommersant 등\nKOTRA\n노보시비르스크 무역관 자료 종합')

In [57]:
# 3. 본문을 chunk로 나누기
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=100,
    separators=["\n\n", "\n", ". ", " ", ""]
)

split_docs = splitter.split_documents(docs)

print("원본 문서 수:", len(docs))
print("분할된 chunk 수:", len(split_docs))

split_docs

원본 문서 수: 10
분할된 chunk 수: 135

[Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘Alfabank’\n에 따르면\n’25\n년 러시아 화장품\n·\n향수 시장 규모는\n1\n조2000억\n루블\n(\n약\n144\n억 달러\n)\n로 전년 대비\n7%-8%\n증가했다\n. 반면\n판매되는 화장품\xa0수량은 감소세로\n, ‘Nilson’\n에 따르면 스킨케어 화장품 판매량은\n1\n년 만에\n13.3%, ‘\n헤어케어\n’\n는\n5.3%, ‘\n바디케어\n’\n는\n4.1%\n줄었다\n.\n시장 규모가 커졌음에도 판매량이 감소한\xa0주요 원인으로\xa0화장품\xa0가격의\xa0증가가 꼽힌다.\n<연도별 러시아 화장품 판매수량\n및 증가율>\n(단위: 십\n억 개\n)\n[자료\n: Businesstat.ru]\n오프라인 판매는 감소하는 반면\xa0온라인\xa0마켓플레이스에서의\xa0판매가\xa0증가하고 있다\n. ’25\n년 온라인\xa0소매기업\n‘Wildberries’\n의 스킨케어 화장품 매출은\xa0전년 대비\n28%,\n색조 화장품 매출은\n20%\n증가했다\n.\n온라인 소매점들은 프리미엄\n,\n친환경\n,\n아시아 브랜드 등 다양한 카테고리의 메뉴를 운영하며 소비자들을 유입시키고 있다\n.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n제조\n·\n판매사 구분 모호\n,\n일반 소매점과\xa0뷰티 전문점간\xa0협력 확대\n물류\n‧\n포장 등 비용 상승은 기업이 제조와 판매를 함께\xa0통제하려는 수직통합 압력으로 작동했다\n.\n소비자의\xa0구매력\xa0약화는\xa0멀티기능성\n,\n가성비\n,\n현지\xa0브랜드\xa0선호를\xa0키웠고\n,\n이는\xa0제조와\xa0판매\xa0모두에서\xa0더\xa0촘촘한\xa0가치사슬\xa0대응을\xa0요구했다\n.\n소매 기업들이 화장품을 직접 제조해 판매하고\n제조사들이 자체 판매망을 구축해 제품을 판매하는 등\n,\n전통적인 기업 형태 구분이 모호해지고\n,\n가치 사슬이\xa0복잡해지는 양상이다\n.\n리테일러들이\nOEM\n을 통해 자체 브랜드 제품을 생산해 판매하고\n,\n별도 유통사들을 통해서만 제품을 공급하던 제조사들도 자체 온라인 마켓플레이스를 구축해 판매하고 있다\n.\n식료품 소매체인\n‘VKUSVILL’\n은 자체 브랜드의 미스트\n,\n핸드크림 등 제품을 화장품 전문 소매체인\n‘Letual’\n사이\n트\n를 통해 판매하고 있고\n,\n소비재\n·\n식료품 소매체인\n‘Magnit’\n도 자체 PB\xa0화장품을 화장품 소매체인\n‘\n골든 애플\n’\n온라인 스토어에서\xa0판매하고 있다\n.\n<뷰티체인\nLetual\n사이트에서 판매되는\nVkusvill(\n식품소매점\n)\n브랜드 화장품>\n* 주\n:'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘\n골든 애플\n’\n온라인 스토어에서\xa0판매하고 있다\n.\n<뷰티체인\nLetual\n사이트에서 판매되는\nVkusvill(\n식품소매점\n)\n브랜드 화장품>\n* 주\n:\n번역기 통해 러시아어를 한국어로 변환\n[자료\n: Letual]\n로컬 브랜드 확산\n물류\n·\n관세\n·\n환율의\xa0급변\xa0상황에서 러시아\xa0브랜드\xa0공급은 지속 확대되고 있다\n.\n러시아\n산업통상부에 따르\n면\n,\n’\n25\n년 향수 및 화장품 시장에서 러시아 제품 점유율은\n68%\n이다\n.\n‘\nBusinessStat\n’\n에 따르면 러시아에서 생산된 스킨케어\n제품 개수는\n‘21\n년\n2\n억9000\n만\n개에서\n‘25\n년\n3\n억7000만\n개로\n26%\n증가했다\n.\n러시아 정부는\n’\n27\n년\n3\n월부터 모든 소비재 소매 체인점에서 러시아산 비식품 제품을 의무적으로 진열하게 하는 법안인 일명\n"\n러시아 제품 진열대\n"\n를 발표했는데 러시아제 화장품\n,\n향수를 우선 대상 제품으로 검토하고 있다\n.\n<\n러시아 상위\n10\n위\n화장품 제조사\n>\n(단위: 백만 루블)\n연번\n회사명\n개요\n지역\n홈페이지\n매출액\xa0(\'25년 기준)\n1\nFaberlic JSC\n화장품, 의류, 액세서리, 신발 및 기타 품목 제조\n모스크바\nfaberlic.com/ru/ru'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content="연번\n회사명\n개요\n지역\n홈페이지\n매출액\xa0('25년 기준)\n1\nFaberlic JSC\n화장품, 의류, 액세서리, 신발 및 기타 품목 제조\n모스크바\nfaberlic.com/ru/ru\n35,668.4\n2\nNTS Gradient LLC\n색조 및 스킨케어 화장품 독점 유통\n모스크바\nwww.gradient.ru\n29,739.88\n3\nUni\nc\no\nsmetic\nLLC\n헤어케어 및 염모제 생산\n상트페테르부르크\nestel.pro\n17,506.67\n4\nArnest JSC\n데오도란트, 안면·전신용 화장품, 식품 등 생산\n스타브로폴 지방 네비노미스크\nwww.arnest.ru\n17,455.63\n5\nZettek LLC\n물티슈 및 건티\n슈 생산\n칼루가 주\nzettek.ru\n9,914.62\n6\nSibair JSC\n스프레이 및 데오도란트 생산\n노보시비르스크\nwww.sibiar.ru\n7,654.56\n7\nGrand AV LLC\n냅킨\n및 마스크 생산\n툴라 주\nwww.grand-av.ru\n6,190.97\n8\nOrganic Pharmaceuticals LLC\n치약 제조\n노브고로드 주\nwww.splat.ru\n5,672.87\n9\nAct LLC\n안면, 전신 및 모발용 케어 화장품 제조\n모스크바"),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='치약 제조\n노브고로드 주\nwww.splat.ru\n5,672.87\n9\nAct LLC\n안면, 전신 및 모발용 케어 화장품 제조\n모스크바\ntheact.ru\n5,402.55\n10\nBiopharmrus LLC\n화장품, 식품 첨가물 및 의\n료용품 OEM 생산\n모스크바주 포돌스크\nbiofarmrus.com\n5,323.84\n* 주: 일부 치약, 물티슈 등 생활소\n비재 제조 포함\n[자료: Gl\nobus]\n홈뷰티\n(a\nt\n‑\nhome beauty)\n확산\n,\n코스메슈티컬\n(\ncosmeceuticals)\n시장 성장\n러시아 뷰티 서비스 가격은 빠르게\xa0인상되고 있다\n. ‘Informer’\n에 따르면,\n’25\n년 헤어\n,\n스파\n,\n숍 등 뷰티 서비스 비용은 전년 대비\n10%-14%\n증가했다\n.\n부동산 임대료 증가\n,\n숙련 인력 급여 인상\n,\n영세업체\nVAT\n면제 한도 변경 등이 가격 인상의 주요 원인으로 꼽힌다.\n‘\n뷰티 기업 및 전문가 협회\n’\n회장인\n‘\n랴 소디코바\n’\n는\n“서비스\n가격 인상의 영향으로\n’\n25\n년\n9-12\n월 기간 러시아인들의 각종 뷰티 숍 방문 빈도가 전년 대비\n20-30%\n감소했다\n.”\n고 말한다\n.'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='‘\n랴 소디코바\n’\n는\n“서비스\n가격 인상의 영향으로\n’\n25\n년\n9-12\n월 기간 러시아인들의 각종 뷰티 숍 방문 빈도가 전년 대비\n20-30%\n감소했다\n.”\n고 말한다\n.\n소비자들은 값비싼 미용 장비를 이용하거나 필러 등을 주입하는 대신 갈바닉\n, LED\n마스크 등 소형 미용 기기를 구입해 집에서 피부를 관리하기 시작했다\n.\n고급 스파 대신 아로마틱 화장품과 스파 용품을 구매해 집에서 목욕을 하는 추세도 나타나고 있다.\n<\n마이크로전류 제품\nMedicube(\n좌\n), LED\n마스크\nL&L SKIN(\n우\n)>\n[자료: Medicube, Ozon]\n노화를 미리 대비하는\n‘\n노화 예방\n’\n에 대한 관심도 높아졌다\n.\n젊은 소비자들 사이에서\xa0자외선 손상\n,\n콜라겐 감소\n,\n표정 주름\n,\n피부 지지대 약화가 주요 관심사로 부상하고 있다.\n‘\n겉만 예뻐 보이는 마사지\n’\n가 아니라 피부 속 림프 순환\n,\n부종 감소\n,\n독소\n·\n노폐물 배출을 돕는 마사지 서비스나 진동 치료가 증가하고 있다\n.\n주사 없이 히알루론산\n,\n비타민 등을 피부에 투입하는 더마드롭\n(Dermadrop),\n콜라겐 등의 생성을 돕는 생체활성화\n(Bioactivation)\n에 대한 관심도 높다\n.'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n주사 없이 히알루론산\n,\n비타민 등을 피부에 투입하는 더마드롭\n(Dermadrop),\n콜라겐 등의 생성을 돕는 생체활성화\n(Bioactivation)\n에 대한 관심도 높다\n.\n과학적으로 입증된 효능을 가진 이른 바 약국에서 판매되는 화장품인 코스메슈티컬\n(cosmeceuticals)\n판매량은 최근\n3\n년간 꾸준히 증가하고 있다\n.\n<러시아 연도별/월별 약국화장품 판매량>\n(단위: 십억\n루블\n)\n[자료\n: DSM Group]\n성분표 확인하는 소비자들, 친환경 오가닉 제품 인기\n시장 규모가 크진 않지만 친환경 오가닉 화장품도 견조한 성장을 이어가고 있다\n.\n제품 성분표에서 화학 첨가제 포함 유무를 확인하는 소비자가 늘고\n,\n그린워싱\n(\n위장환경주의\n)\n에 대한 관심도 높아져 국제\n친환경 제품 인증서를 받으려는 기업들도 많아지고 있다\n.\n천연 화장품 수요가 가장 큰 제품군은\n‘\n얼굴 케어\n’\n이며\n,\n황산염 무함유 샴푸\n,\n오일 함유 린스 등\n‘\n헤어 케어\n’\n에 대한 수요도 높다\n.\n립스틱 같은 제품에 천연 원료 함유나 포장 재활용 문구도 많이 나타난다\n.\n러시아 정부는\n"Organic"\n라벨을 도입하는 한편\n,\n’\n25.10\n월에\n‘\n예비 국가 표준\n’'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n립스틱 같은 제품에 천연 원료 함유나 포장 재활용 문구도 많이 나타난다\n.\n러시아 정부는\n"Organic"\n라벨을 도입하는 한편\n,\n’\n25.10\n월에\n‘\n예비 국가 표준\n’\n을 승인\n,\n특정 요건을 충족하는 제품에 한해\n‘\n자연\n’\n,\n‘\n유기농\n’\n,\n‘그린\n’\n등의 단어를 쓸 수 있도록\xa0하는\xa0규제를 준비하기 시작했다\n.\n<동물 테스트 반대 표방 러시아 천연 화장품 브랜드\nMatsesta>\n[자료: Matsesta]\n복고풍의 귀환과 스토리\xa0감성 마케팅\n뷰티 업계는 수년간 이어져 온\n‘\n클린 걸\n(Clean Girl)’\n과\n‘\n미니멀리즘\n’\n에서 벗어나\n,\n과감하고 다채로운\n2000\n년대 감성으로 회귀하고 있다\n.\n계속되는 러-우 사태가 과거에 대한 향수를 자극한 측면이\xa0있다\n.\n단순히 따라 하는 화장이나 꾸안꾸 스타일이 아닌\n,\xa01990\n년대의\xa0섹시함과\n‘\n개성 중심의 뷰티\n’\n가 주목받고 있다\n.\xa0특히\n젊은층에서\n2000\n년대 스타일의 글리터 섀도우\n,\n그라데이션 립 등이 유행이다\n. 최근\xa0러시아\n패션 브랜드\n‘Gloria Jeans’\n는 러시아\nSNS\n인\n‘VK’\n와\n2000\n년\nY2K\n를 주제로 한 콜라보레이션 마케팅을 진행했다\n.\n<'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='. 최근\xa0러시아\n패션 브랜드\n‘Gloria Jeans’\n는 러시아\nSNS\n인\n‘VK’\n와\n2000\n년\nY2K\n를 주제로 한 콜라보레이션 마케팅을 진행했다\n.\n<\n‘Gloria Jeans’\n와\n‘VK.com’\n콜라보레이션\n>\n[자료: Gloria Jeans]\n기능이나 가격보다\n‘\n브랜드가 전하는 이야기\n’\n에 열광하는 소비자들이\xa0늘고 있다\n.\n단순한 상품 구매를 넘어\n,\n브랜드 철학을 공유하고 정서적인 만족을 얻을 수 있는\n‘\n감성 마케팅\n’\n과\n‘\n스토리텔링\n’\n을 원하는 고객들이 많다\n.\n러시아 기업\n‘Natura Siberica’\n는 러시아 전통 도자기\n‘\n그젤\n(Gzhel)’\n문양을 활용한 디자인을 통해 브랜드에 애국심과 민족적 정체성을 입혔다\n.\n러시아인의 향수와 문화적 자부심을 자극하는 감성 마케팅 사례로 꼽힌다\n.\n‘Erinel’\n사는\n‘\n엘프의 전설\n’\n이라는 독특한 세계관을 브랜드에 녹여냈다\n.\n엘프의 마법 이야기를 모든 제품과 디자인에 담아냈다\n.\n이러한 차별화된 세계관은 강력한 팬덤을 형성하는 원동력이 됐다\n.\n<러시아 전통 디자인을 차용한\nNatura Siberica,\n엘프 스토리를 활용한\n‘Erinel’>'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n이러한 차별화된 세계관은 강력한 팬덤을 형성하는 원동력이 됐다\n.\n<러시아 전통 디자인을 차용한\nNatura Siberica,\n엘프 스토리를 활용한\n‘Erinel’>\n[자료: Natura Siberica, Erinel\n]\n마케팅 흐름은 이제\n‘\n성능과 효율\n’\n을 강조하던 시대에서\n‘\n공감과 가치\n’\n를 공유하는 시대로 넘어왔다\n.\n소비자는 입술을 붉게 칠하는 립스틱을 사는 것이 아니라\n,\n그 립스틱이 담고 있는 브랜드 철학을 자신의 라이프스타일에 입히고 있는 셈이다\n.\n피부 관리 시작한 러시아 남성들\n, K-Pop\n도 영향\n건강한 피부는 젊음과 성공의 상징이라는 인식이 남성들에게 확산되고 있다\n.\n‘\nInfoline\n’\n에 따르면\n’\n25\n년 남성 화장품 판매는 전년 대비\n20%\n증가했는데\n,\n이는 여성 제품 증가율\n(13%)\n보다 높은 수치다\n.\n‘\nCommerce\n’\n에 따르면,\n’\n25\n년 남성 화장품 부문에서 소매체인\n‘\nWildberries\n’\n는\n247\n억 루블\n(\n약\n2억9600만 달러\n)\n,\n‘\nOzon\n’\n은\n145\n억 루블\n(약\n1억7400만 달러\n)\n의 매출액을 기록했다\n.\n‘\nCollagene 3D Medical\n’\n사의 전무이사'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='약\n2억9600만 달러\n)\n,\n‘\nOzon\n’\n은\n145\n억 루블\n(약\n1억7400만 달러\n)\n의 매출액을 기록했다\n.\n‘\nCollagene 3D Medical\n’\n사의 전무이사\n‘\n나제즈다 볼코바\n’\n는 무역관과의 인터뷰에서\n“최근\n러시아 남성들은\n셰\n이빙\xa0로션 뿐만 아니라\n,\n보습제\n,\n세럼\n,\n자외선차단제\n,\n화장품을 구매한다\n.”\n고\xa0언급했다\n. 한편\n뷰티체인\n‘\nIl De Bote\n’\n의 메이크업 아티스트인\n‘\n아나스타샤 율리나\n’\n는\n“\n남성들에게 안티 에이징 화장품이 인기\n”\n라면서\n“\n남성 화장품의 인기에\nK-Pop\n이 미친 영향을 무시할 수 없다.\n”\n고 밝혔다.\n<맥주 캔 디자인의 남성용 샤워젤 제품\n(\n좌\n), Wildberries\n남성용 화장품\xa0검색 결과\n(\n우\n)>\n[자료: Wildberries\n]\n뷰티 전문 리테일러들의 서비스 전문화와\nAI\xa0적용 확대\n화장품\xa0소매점들의 서비스는 더욱 전문화되고 있다\n.\n다양한 제품과 서비스에 대해\xa0충분한 사전 교육을 받은 종업원들이 먼저 고객에게 다가가 피부 컨디션을\xa0묻고 화장품을 추천한다\n.\n소비자들의 반응과 문의를 기다리던 과거와 달라진 모습이다\n.\n매\n장\n인\n테\n리\n어\n디\n자\n인도\n트\n렌\n드'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='.\n소비자들의 반응과 문의를 기다리던 과거와 달라진 모습이다\n.\n매\n장\n인\n테\n리\n어\n디\n자\n인도\n트\n렌\n드\n에\n맞\n게\n수시로\n바\n꾸\n고\n,\n브\n랜\n드\n와\n제\n품\n도\n소\n비\n자\n들\n이\n보\n기\n편\n하\n게\n분류해\xa0배치하고 있다.\xa0감\n각\n적인 디자인의\xa0각종\xa0특별 판촉\xa0공간, 체험존도\xa0운영한다.\n<Golden Apple 노보시비르스크 지점 내 제품 체험존>\n[자료: Golden Apple\n]\nAI 활용도 늘고 있다.\xa0AI를 통해\n피부 진단과 제품 선택을 지원하는\n‘BeautyScan’\n서비스는 소매체인\n‘Magnit Cosmetic’\n의\n2500\n개 매장에서 제공되고 있다\n.\n서비스 도입 이후 사용자들의 평균 구매 금액이\n29%\n증가했으며 매장 방문 빈도도 운영 전 대조군 대비\n35%\n증가한 것으로 나타났다\n.\n러시아 화장품 제조사이자 피부진단 기업인\n‘GELTEK’\n는 얼굴 이미지를 통해 피부 문제를 진단하는 러시아 최초의\nAI\n서비스\n‘Skin Assistant’\n를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='를 제공하고 있다\n.\n모공확장\n,\n주름\n,\n색소침착 등\n12\n가지 피부 문제를 진단해 제품과 서비스를 추천한다\n.\n<AI\xa0피부진단 및 제품추천 서비스 Skin Assistant>\n[자료: Skin Assiatant\n]\nK-Beauty 트렌드\xa0지속\n‘\nS&P Global\n’\n에 따르면,\n‘25\n년 러시아의 화장품\n(HS Code 3404)\n수입 규모는 약\n12\n억 달러로 전년 대비\n7.8%\n성장했다\n.\n이 중 한국산 화장품 수입액은\n3\n억6000만\n달러로 전년대비\n12%\n이상 성장\n,\n러시아 내\n1\n위 수입국 지위를 유지하고 있다\n. 2\n위인 프랑스\n(\n1\n억8000만\n달러\n)\n와는 약\n2\n배의 격차이다\n.\n’\n25\n년\n4\n월\n,\n러시아 정부는 비우호국산 화장품 및 향수에 대한 고율 관세 부과 대상에서 한국을 전격 제외했다\n.\n이에 따라\xa0과거에 부과되던\n35%\n의 고율 관세 대신\n,\n한국산 제품은\n6.5%\n의 표준 관세율을 적용받게 됐다\n.\n대상 품목은 향\n수\n,\n화장수\n,\n색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='색조\n화장품\n(\n립스틱\n,\n파우더 등\n),\n기초 스킨케어\n,\n헤어케어 등이다\n.\n관세 인하 효과로 인해 가격 경쟁력 확보가 용이해진 면이 있다.\n<러시아의\xa0연도별 화장품 수입액\n(HS Code 3304:\n미용\n·\n메이크업용 및 기초화장품류\n)>\n(단위: US$ 천, %)\n순번\n국가\n수입액\n증가율\n2025/2024\n2023\n2024\n2025\n총액\n1,103,557\n1,103,011\n1,189,001\n7.80\n1\n대한민국\n316,157\n322,347\n361,229\n12.06\n2\n프랑스\n130,437\n148,342\n180,498\n21.68\n3\n중국\n122,882\n113,498\n155,169\n36.71\n4\n독일\n72,753\n85,998\n91,707\n6.64\n5\n폴란드\n138,545\n110,257\n85,555\n-22.40\n6\n이탈리아\n37,126\n83,896\n75,595\n-9.89\n7\n카자흐스탄\n25,240\n44,150\n62,459\n41.47\n8\n이스라엘\n40,646\n34,642\n33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='33,681\n-2.77\n9\n벨기에\n4,537\n15,604\n27,432\n75.80\n10\n스페인\n17,214\n44,140\n24,794\n-43.83\n[자료: S&P Global]\n<화장품\xa0체인점 Golden\xa0Apple내\xa0한국화장품 섹션 중 일부>\n[자료:\nKOTRA\n노보시비르스크\n무역관 자체 촬영]\n시사점\n경제제재 이후 해외 브랜드 철수\n,\n병행수입\n,\n물류 상황 변화가\xa0겹치면서 러시아의 기존 수입 브랜드 유통 구조가 변화해왔다\n.\n이 과정에서 기존 소매업체들은 단순 판매보다 새로운 브랜드 포트폴리오 확보와 자체 대응이 중요해졌다\n.\n러시아 로컬 브랜드는 수요 공백을 메우며 빠르게 성장했고\n,\n일부는 생산까지 확대했다\n.\n러시아 시장에서는\n“\n매장에 올리는 것\n”\n보다\n“\n소비자의 욕실과 화장대에 들어가는 것\n”\n이 중요해졌다는 표현이 나올 정도로\n,\n브랜드 경쟁이 치열해졌다\n.\n이는 단순 유통보다 브랜드 소유와 제품 기획 역량이 중요해졌다는 의미이다\n.\n전시 고물가 추세가 지속되는 상황에서,\n우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다'),
 Document(metadata={'row_id': 0, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938', 'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'}, page_content='우리 기업들의 발 빠른 대응과\xa0점유율 공고화\xa0전략이 필요하다\n.\n러시아 소비자들은 수입 화장품을 선호하지만\n,\n그만큼 확실한 효능을 기대한다\n.\xa0독특한 성분과\xa0입증된\xa0효과를 갖춘 제품을\xa0지속적으로\xa0제안하고,\n인증, 물류, 마케팅\xa0등에서 체계적이고 신속한 대응 체계를 갖추는 한편, 브랜드가 가진 철학을 정직하고 일관성 있게 전달할 필요가 있다. 제품의 수출과 함께 K-Beauty의 프리미엄\xa0이미지를\xa0구축해 나갈\xa0시기이다.\n러시아 제조사\n‧\n뷰티전문체인과의 다각적인 파트너\n십\n구축\n,\nOEM\n‧\nODM\n협력\n,\n대형 디스트리뷰터 뿐만 아니라 지방의 유력 중견 바이어들과의\xa0네트워크\xa0확대\xa0등을 검토하고\n,\xa0홈뷰티,\n약국용 화장품\n,\n친환경\n,\n남성용\xa0제품 등\xa0성장 분야에도 관심을 가질 필요가 있다\n. 러시아\xa0수출을\xa0처음 추진하는\xa0기업들은 InterCharm(\nhttps://en.intercharm.ru/\n) 등\n전문\n전시\n회에\n참가하는 것도\n시장\xa0파악과\xa0관심\xa0바이어\xa0발굴에 효과적인\xa0방안이 될 수 있다.\n자료\n: Kommersant 등\nKOTRA\n노보시비르스크 무역관 자료 종합'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='요약\n도미니카공화국은 2025년 12월 법률 제98-25호 시행을 통해 플라스틱·발포(폼) 제품의 수입 및 유통 규제를 강화하였다. 동 법은 생분해성 인증 의무화와 생산자책임재활용제도(EPR) 확대를 주요 내용으로 하며, 발포폴리스티렌(EPS) 소재의 빨대·식기류·뚜껑·컵·용기 등은 적정한 환경 인증 없이는 수입이 금지된다. (법령 명칭 : 통합 고형폐기물 관리 및 공동처리법 개정안 (법률 제98-25호) / 현지어 명칭 : Ley Núm. 98-25 que modifica la Ley General de Gestión Integral y Coprocesamiento de Residuos Sólidos)\n2026\n년 2월 15일 동 법 발효 이후 관련 품목 통관 단계에서 도미니카공화국 관세청(DGA)이 인증 여부를 확인하고 있으며, 인증 서류 미비 시 통관 지연 또는 반송 사례가 발생하고 있는 것으로 파악된다.'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='이번 규제는 환경정책의 변화에 그치지 않고 도미니카공화국 수입시장의 거래 조건에도 영향을 주고 있다. 한국 수출기업이 현지 바이어에게 직접 납품하는 구조라면 부담금이나 EPR 의무의 직접 대상은 아닐 수 있으나, 현지 수입업체의 규제 부담이 인증 자료 요청, 포장재 변경 요구, 가격 재협상 등의 형태로 공급업체에 전가될 수 있다.\n한편 기업 부담금 수준을 두고 현지 상공계와 정부·국회 간 협의가 진행 중이다(2026년 4월 현재). 부담금 체계는 변동 가능성이 있으나, 수입 금지 및 인증 의무화 조항은 그대로 적용되고 있어 대 도미니카공화국 수출기업 그리고 현지에 진출한 기업들의 지속적인 모니터링과 대응이 요구된다.\n개요'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='개요\n법률 제98-25호는 기존 통합 고형폐기물 관리법(제225-20호)을 개정한 것으로, 2025년 12월 15일 공포되었다. 기존 법이 폐기물 관리 일반 기준에 초점을 맞춘 것과 달리, 개정법은 소재(material) 단위로 규제 대상을 설정한다. 특정 산업에 한정되지 않고, 발포 또는 비생분해성 플라스틱 소재를 사용하는 모든 제품이 규제 검토 대상에 포함된다. 이에 따라 완제품 수출기업뿐 아니라 현지 제조업체에 포장재나 부자재를 공급하는 기업도 영향권에 놓일 수 있다.\n규제 대상 주요 품목은 다음과 같다.\n폼(발포폴리스티렌, EPS) 소재 : 빨대·포크 나이프·숟가락·뚜껑·컵 등 (2026.02.15부터 즉시 수입 금지, 인증 없는 경우)\n일반 플라스틱 소재 : 빨대·포크 나이프·숟가락 (법 시행 후 12개월 이내 유통 금지, 인증 없는 경우)\n일회용 비닐봉투 : 법 시행 후 12개월 이내 무상 제공 금지\n규제 예외 품목으로는 의료·병원·실험실용 플라스틱 용기, 도로공사 및 건설용 플라스틱이 인정된다.\n또한 경첩형 뚜껑이 일체형으로 부착된 폼 식품 용기(예: 힌지 뚜껑 도시락 용기)는 유통 금지 조항에서 예외로 명시되어 있다.'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='또한 경첩형 뚜껑이 일체형으로 부착된 폼 식품 용기(예: 힌지 뚜껑 도시락 용기)는 유통 금지 조항에서 예외로 명시되어 있다.\n다만 예외 인정을 위해서는 해당 사유를 설명하는 서류 준비가 필요하다.\n생분해성 인증 기준은 시험기관의 검증을 통해 1년 내 최소 20%, 또는 최대 5년 내 9\n0% 이상의 분해율을 충족해야 한다\n.\n다만\xa0도미니카공화국품질원(INDOCAL)이\xa0세부\xa0기술\xa0기준\xa0및\xa0인증\xa0검증\xa0절차는\xa0아직\xa0마련\xa0중에\xa0있어,\xa0통관\xa0현장에서는 기준 적용 방식 등 관련하여 다소간의 혼선이 빚어질 수 있다. 현재\n국제\n규격에\n따른\n해외\n인증이\xa0다소\n광범위하게\n인정되고\xa0있으나,\xa0추후\xa0기준과\xa0절차\xa0정립\xa0후에는\xa0항목별로\xa0정확한\xa0준용이\xa0필요할\xa0것으로\xa0보인다.\n동\n법이 권장하는 대체 소재로는 종이, 재활용·생분해성 판지, 사탕수수\xa0부산\n물\n(bagasse), 대나무, 식물성 섬유, 퇴비화 가능 소재(compostable), 인증된 생분해성 소재, 재사용 가능 용기 등이 있다.\n집행\n기관\n관련,\n관세청(DGA)이\n통관 시\n인증\n서류를'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='집행\n기관\n관련,\n관세청(DGA)이\n통관 시\n인증\n서류를\n확인하고, 도미니카공화국품질원(INDOCAL)이 기술 검증을 지원하며, 환경부(Ministerio de Medio Ambiente y Recursos Naturales)가 제\n도\n전반의\n준수를\n감독한다.\n제도 시행 및 단계별 이행 일정\n동 법은 수입 절차와 국내 시장 운영 전반에 영향을 미치는 단계적 시행 조치를 규정하고 있다.\n<법령 시행 관련 일정>\n구분\n시행일\n주요 내용\n법률 제98-25호 시행\n2025.12.15\n개정된 폐기물관리 체계 시행\n폼 제품 수입금지\n2026.02.15\n빨대·식기·뚜껑·컵 등 미인증폼 제품 수입 금지\n폐기물 배출자등록\n2026.06.15\n환경부 대상사업자 등록 의무화\n일반 플라스틱식기·빨대 유통 금지\n2026.12.15\n미인증 플라스틱빨대·포크·숟가락·나이프유통 금지\n생산자책임재활용제도(Extended Produce Responsibility) 관리계획 제출\n2026.12.15\n폐기물 관리계획제출 의무\n무상 비닐봉투제공 금지\n2026.12.15\n일회용 비닐봉투무상 제공 금지\n발포 제품 대체전환\n2027.12.15\n친환경 대체소재로 전환\n지자체 분리배출프로그램'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='무상 비닐봉투제공 금지\n2026.12.15\n일회용 비닐봉투무상 제공 금지\n발포 제품 대체전환\n2027.12.15\n친환경 대체소재로 전환\n지자체 분리배출프로그램\n2028.12.15\n지방정부 선택적수거 프로그램 확대\n실무적으로는 법률상 일정과 실제 통관·인증 운용 사이에 차이가 발생할 수 있다. INDOCAL의 세부 기술 기준이 확정되는 과정에서 혼선이 발생할 가능성이 있으므로, 현지 바이어가 실제로 어떤 서류를 요구받고 있는지를 확인하는 것이 단순히 법률 시행일을 확인하는 것보다 실질적인 대응에 도움이 될 것으로 사료된다.\n생산자책임재활용제도(EPR) 및 기업 부담금 관련 현황'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='생산자책임재활용제도(EPR) 및 기업 부담금 관련 현황\n강화된 제도 하에서, 도미니카공화국 시장에 규제 대상 소재를 유통하는 기업은 수거, 재활용 등 사후 폐기물 관리에 대한 책임을 부담한다. 비닐봉투·플라스틱병 생산자는 법 시행 후 12개월 이내에 폐기물 회수·처리·처분 프로그램에 참여해야 한다. 한국에서 도미니카공화국으로 제품을 수출하는 기업이 곧바로 현지 부담금 납부 대상이 되는 구조는 아닌 것으로 파악된다. 다만 현지 수입업체, 유통업체, 제조업체가 관련 의무와 부담금을 부담하게 되면, 해당 비용이 인증 자료 요청, 발주 축소, 포장재 변경 요구, 가격 재협상 등의 형태로 한국 공급업체에 전가될 수 있다.'),
 Document(metadata={'row_id': 1, 'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022', 'keywords': '#도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제'}, page_content='동 법령을 통해 정부는 기업의 연간 매출액을 기준으로 산정되는 특별부담금(Contribución Especial) 제도를 도입하였다. 이 부담금은 EPR 의무 대상인 생산자·수입자·유통업자에 한정되지 않으며, 도미니카공화국 내에 등록된 모든 공·사법인(todas las personas jurídicas, públicas y privadas) 에 적용된다. 즉, 플라스틱 제품을 직접 생산하거나 수입하지 않더라도, 사업 운영 과정에서 폐기물을 발생시키는 법인이라면 납부 의무를 지게 된다. 국세청(DGII)이 안내한 바에 따르면 부담금은 연간 매출액 구간에 따라 RD$3,000에서 RD$675,000(약 50~11,250달러) 수준으로 규정되어 있으며, 수익 발생 여부와 관계없이 의무 납부 구조로 설계되어 있다. 이에 대해 도미니카공화국 산업협회(AIRD), 자유무역지대협회(Adozona), 상인연합회 등 주요 경제단체는 매출액 기준 부과 방식의 형평성 문제를 지적하고 있다. 매출이 유사하더라도 실제 폐기물 배출량은 업종에 따라 크게 다를 수 있어, 현행 구조가 조세 비례 원칙에 반한다는 것이 업계의 주된 주장이다.'),

In [23]:
# 4. Qwen3-Embedding MLX 4-bit 모델 로드
from mlx_embeddings import load
import mlx.core as mx
import numpy as np

model, tokenizer = load("majentik/Qwen3-Embedding-0.6B-MLX-4bit")

/Users/b58230717/Desktop/2026_2/aaa/project/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 132451.71it/s]

In [24]:
# 5. split_docs를 임베딩하기
doc_texts = [doc.page_content for doc in split_docs]

inputs = tokenizer(
    doc_texts,
    padding=True,
    truncation=True,
    max_length=8192,
    return_tensors="mlx"
)

outputs = model(
    inputs["input_ids"],
    attention_mask=inputs["attention_mask"]
)

doc_embeddings = np.array(outputs.text_embeds).astype("float32")

print("임베딩 shape:", doc_embeddings.shape)

NameError: name 'split_docs' is not defined

In [48]:
# 6. FAISS 인덱스 만들기
import faiss

dim = doc_embeddings.shape[1]

index = faiss.IndexFlatIP(dim)
index.add(doc_embeddings)

print("FAISS에 저장된 chunk 수:", index.ntotal)

FAISS에 저장된 chunk 수: 135

In [18]:
# 7. 자연어 검색어 임베딩하기
query = "러시아 화장품 시장 전망"
task = "Given a Korean natural language search query, retrieve relevant KOTRA news passages."
query_text = f"Instruct: {task}\nQuery: {query}"

query_inputs = tokenizer(
    [query_text],
    padding=True,
    truncation=True,
    max_length=8192,
    return_tensors="mlx"
)

query_outputs = model(
    query_inputs["input_ids"],
    attention_mask=query_inputs["attention_mask"]
)

query_embedding = np.array(query_outputs.text_embeds).astype("float32")

print("query embedding shape:", query_embedding.shape)

NameError: name 'tokenizer' is not defined

In [55]:
# 8. 관련 chunk 검색하기
k = 50
scores, indices = index.search(query_embedding, k)

print("scores:", scores)
print("indices:", indices)

scores: [[0.7222228  0.7166976  0.6802507  0.6531437  0.638294   0.6031742
  0.59983474 0.57198143 0.5612768  0.5395051  0.5313067  0.521901
  0.5161246  0.4962517  0.48319215 0.46648148 0.44779748 0.4474364
  0.44293654 0.43524218 0.4186027  0.41467464 0.41008562 0.41000536
  0.40273744 0.38160598 0.37726542 0.37428907 0.3736775  0.36411145
  0.36041993 0.36041647 0.35973975 0.35939303 0.35821337 0.35689485
  0.35036105 0.34969148 0.34916392 0.34783107 0.3447735  0.34394708
  0.3413197  0.33289143 0.3314852  0.33021438 0.32837635 0.3283474
  0.32746425 0.32400206]]
indices: [[  0   2  14  12   4   9  13   7   6  10   5  96  91   3   8  97  92  90
   98 131 112 125  11  93 123  95 102 109 122   1 117 107 121 100  99 101
  132 133  79 120 105  94 118 128  82 130 113 114 103 106]]

In [56]:
# 9. 검색 결과 본문 그대로 출력
top_urls = []
seen_urls = set()

for score, idx in zip(scores[0], indices[0]):
    doc = split_docs[idx]
    url = doc.metadata.get("url", "")

    if url == "":
        continue

    if url not in seen_urls:
        seen_urls.add(url)
        top_urls.append({
            "url": url,
            "score": float(score),
            "row_id": doc.metadata.get("row_id"),
            "keywords": doc.metadata.get("keywords")
        })

    if len(top_urls) >= 5:
        break

top_urls

[{'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938',
  'score': 0.7222228050231934,
  'row_id': 0,
  'keywords': '#러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출'},
 {'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240772',
  'score': 0.52190101146698,
  'row_id': 7,
  'keywords': '#남성, #화장품, #뷰티, #멘즈뷰티, #K-Beauty, #일본, #일본 시장'},
 {'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240926',
  'score': 0.4474363923072815,
  'row_id': 6,
  'keywords': '#방재, #지진, #방범, #보안, #열사병'},
 {'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241034',
  'score': 0.4352421760559082,
  'row_id': 9,
  'keywords': '#offshore, #해양에너지, #기자재, #미국, #해양, #장비, #공급, #운영지원, #MRO, #설비, #기기, #밸브, #피팅'},
 {'url': 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240791',
  'score': 0.41860270500183105,
  'row_id': 8,
  'keywords': '#푸드테크, #DX, #AI, #식품, #자동화, #로봇'}]

# Qwen3-Embedding-0.6B-MLX-4bit 임베딩 (chunking x)

In [25]:
import pandas as pd
from langchain_core.documents import Document
from langchain_core.documents import Document



df = pd.read_csv("data/kotra_news_body.csv", encoding="utf-8-sig")
df.columns = df.columns.str.replace("\ufeff", "", regex=False).str.strip()

df = df[
    df["본문"].notna() &
    (df["본문"].astype(str).str.strip() != "")
].reset_index(drop=True)

df_sample = df.iloc[:10]

# 2. LangChain Document 만들기
docs = []

for idx, row in df_sample.iterrows():
    doc = Document(
        page_content=row["본문"],
        metadata={
            "row_id": idx,
            "url": row.get("게시물 URL", ""),
            "keywords": row.get("키워드", "")
        }
    )
    docs.append(doc)

doc_texts = [doc.page_content for doc in docs]

inputs = tokenizer(
    doc_texts,
    padding=True,
    truncation=True,
    max_length=32768,
    return_tensors="mlx"
)

outputs = model(
    inputs["input_ids"],
    attention_mask=inputs["attention_mask"]
)

doc_embeddings = np.array(outputs.text_embeds).astype("float32")
print("임베딩 shape:", doc_embeddings.shape)

/var/folders/wx/rj6wt5wn1yl8195jd9gqn5jc0000gn/T/ipykernel_3550/603946691.py:7: DtypeWarning: Columns (0: 일자리구분명) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/kotra_news_body.csv", encoding="utf-8-sig")

임베딩 shape: (10, 1024)

In [26]:
import faiss

dim = doc_embeddings.shape[1]

index = faiss.IndexFlatIP(dim)
index.add(doc_embeddings)

print("FAISS 저장 문서 수:", index.ntotal)

FAISS 저장 문서 수: 10

In [27]:
query = "러시아 화장품 시장 전망"

task = "Given a Korean natural language search query, retrieve relevant KOTRA news articles."
query_text = f"Instruct: {task}\nQuery: {query}"

query_inputs = tokenizer(
    [query_text],
    padding=True,
    truncation=True,
    max_length=32768,
    return_tensors="mlx"
)

query_outputs = model(
    query_inputs["input_ids"],
    attention_mask=query_inputs["attention_mask"]
)

query_embedding = np.array(query_outputs.text_embeds).astype("float32")

scores, indices = index.search(query_embedding, 5)

for rank, idx in enumerate(indices[0], start=1):
    doc = docs[idx]
    score = scores[0][rank - 1]

    print("=" * 80)
    print(f"[검색 결과 {rank}]")
    print("score:", score)
    print("row_id:", doc.metadata.get("row_id"))
    print("url:", doc.metadata.get("url"))
    print("keywords:", doc.metadata.get("keywords"))

================================================================================
[검색 결과 1]
score: 0.7289356
row_id: 0
url: https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938
keywords: #러시아, #화장품, #뷰티, #뷰티트렌드, #화장품 수출
================================================================================
[검색 결과 2]
score: 0.5550666
row_id: 2
url: https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240931
keywords: #러시아, #식품, #외식, #식당, #호텔, #레스토랑, #Horeca, #전시회, #패스트푸드, #스트릿푸드, #커피, #식품가공기계, #주방, #푸드
================================================================================
[검색 결과 3]
score: 0.48456842
row_id: 7
url: https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240772
keywords: #남성, #화장품, #뷰티, #멘즈뷰티, #K-Beauty, #일본, #일본 시장
================================================================================
[검색 결과 4]
score: 0.41018942
row_id: 8
url: https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240791
keywords: #푸드테크, #DX, #AI, #식품, #자동화, #로봇
================================================================================
[검색 결과 5]
score: 0.35943317
row_id: 1
url: https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022
keywords: #도미니카공화국, #수입 규제, #고형 폐기물법, #환경 규제 준수, #플라스틱 규제

In [62]:
top_urls = []

for idx in indices[0]:
    doc = docs[idx]
    top_urls.append(doc.metadata.get("url"))

top_urls

['https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240938',
 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240931',
 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240772',
 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=240791',
 'https://dream.kotra.or.kr/user/extra/kotranews/bbs/linkView/jsp/Page.do?dataIdx=241022']

In [ ]:
# 32K 안에 들어오는지 확인
token_lengths = []

for text in df["본문"].iloc[:1000]:
    encoded = tokenizer(
        str(text),
        truncation=False,
        padding=False
    )
    token_lengths.append(len(encoded["input_ids"]))

pd.Series(token_lengths).describe()

count     1000.000000
mean      4552.194000
std       2384.714679
min         37.000000
25%       3064.250000
50%       4151.500000
75%       5825.500000
max      18081.000000
dtype: float64

## 전체 기사 단위 Qwen3 임베딩 저장

In [28]:
import gc
import json
from pathlib import Path

import faiss
import mlx.core as mx
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

try:
    model
    tokenizer
except NameError:
    from mlx_embeddings import load
    model, tokenizer = load("majentik/Qwen3-Embedding-0.6B-MLX-4bit")

CSV_PATH = Path("data/kotra_news_body.csv")
OUT_DIR = Path("data/faiss/kotra_news_body_qwen3_article")
BATCH_DIR = OUT_DIR / "batches"
INDEX_PATH = OUT_DIR / "index.faiss"
METADATA_PATH = OUT_DIR / "metadata.parquet"
CONFIG_PATH = OUT_DIR / "config.json"

MODEL_NAME = "majentik/Qwen3-Embedding-0.6B-MLX-4bit"
BATCH_SIZE = 1
MAX_LENGTH = 32768
CSV_ENCODING = "utf-8-sig"
TEXT_COL = "본문"

OUT_DIR.mkdir(parents=True, exist_ok=True)
BATCH_DIR.mkdir(parents=True, exist_ok=True)

df_all = pd.read_csv(CSV_PATH, encoding=CSV_ENCODING, dtype=str, keep_default_na=False)
df_all.columns = df_all.columns.str.replace("\ufeff", "", regex=False).str.strip()
df_all["source_row_id"] = df_all.index

df_embed = df_all[df_all[TEXT_COL].astype(str).str.strip() != ""].reset_index(drop=True)
print("임베딩 대상 행 수:", len(df_embed))

metadata_cols = [
    "source_row_id",
    "뉴스제목",
    "게시물 URL",
    "키워드",
    "뉴스게시일자",
    "국가",
    "지역",
    "본문",
]
metadata_cols = [col for col in metadata_cols if col in df_embed.columns]
num_batches = (len(df_embed) + BATCH_SIZE - 1) // BATCH_SIZE

for batch_id in tqdm(range(num_batches), desc="Qwen3 기사 임베딩"):
    emb_path = BATCH_DIR / f"embeddings_{batch_id:06d}.npy"
    meta_path = BATCH_DIR / f"metadata_{batch_id:06d}.parquet"

    if emb_path.exists() and meta_path.exists():
        continue

    start = batch_id * BATCH_SIZE
    end = min(start + BATCH_SIZE, len(df_embed))
    batch_df = df_embed.iloc[start:end].copy()
    texts = batch_df[TEXT_COL].astype(str).tolist()

    inputs = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH,
        return_tensors="mlx"
    )
    outputs = model(
        inputs["input_ids"],
        attention_mask=inputs["attention_mask"]
    )

    embeddings = np.array(outputs.text_embeds).astype("float32")
    faiss.normalize_L2(embeddings)
    np.save(emb_path, embeddings)

    batch_meta = batch_df[metadata_cols].copy()
    batch_meta.insert(0, "faiss_id", range(start, end))
    batch_meta.to_parquet(meta_path, index=False)

    del inputs, outputs, embeddings, batch_df, batch_meta, texts
    gc.collect()
    mx.clear_cache()

batch_embedding_paths = sorted(BATCH_DIR.glob("embeddings_*.npy"))
batch_metadata_paths = sorted(BATCH_DIR.glob("metadata_*.parquet"))

if len(batch_embedding_paths) != len(batch_metadata_paths):
    raise ValueError("임베딩 batch와 metadata batch 개수가 다릅니다.")

index = None
for emb_path in tqdm(batch_embedding_paths, desc="FAISS 인덱스 생성"):
    embeddings = np.load(emb_path).astype("float32")
    if index is None:
        index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)

metadata = pd.concat(
    [pd.read_parquet(path) for path in batch_metadata_paths],
    ignore_index=True
)
metadata["faiss_id"] = range(len(metadata))

faiss.write_index(index, str(INDEX_PATH))
metadata.to_parquet(METADATA_PATH, index=False)

config = {
    "model_name": MODEL_NAME,
    "source_csv": str(CSV_PATH),
    "index_path": str(INDEX_PATH),
    "metadata_path": str(METADATA_PATH),
    "batch_size": BATCH_SIZE,
    "max_length": MAX_LENGTH,
    "chunking": False,
    "normalized_l2": True,
    "rows": int(len(metadata)),
    "embedding_dim": int(index.d),
}
CONFIG_PATH.write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")

print("FAISS index:", INDEX_PATH)
print("metadata:", METADATA_PATH)
print("rows:", index.ntotal)
print("dim:", index.d)

임베딩 대상 행 수: 94550

Qwen3 기사 임베딩:   3%|▎         | 2386/94550 [02:35<1:40:07, 15.34it/s]

KeyboardInterrupt:

In [4]:
import faiss
import numpy as np
import pandas as pd

index = faiss.read_index(str(INDEX_PATH))
metadata = pd.read_parquet(METADATA_PATH)

query = "러시아 화장품 시장 전망"
task = "Given a Korean natural language search query, retrieve relevant KOTRA news articles."
query_text = f"Instruct: {task}\nQuery: {query}"

query_inputs = tokenizer(
    [query_text],
    padding=True,
    truncation=True,
    max_length=MAX_LENGTH,
    return_tensors="mlx"
)
query_outputs = model(
    query_inputs["input_ids"],
    attention_mask=query_inputs["attention_mask"]
)

query_embedding = np.array(query_outputs.text_embeds).astype("float32")
faiss.normalize_L2(query_embedding)

scores, indices = index.search(query_embedding, 10)

results = metadata.iloc[indices[0]].copy()
results.insert(0, "score", scores[0])
results[["score", "뉴스제목", "게시물 URL", "키워드", "뉴스게시일자", "국가"]].head(10)

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char *) at /Users/runner/work/faiss-wheels/faiss-wheels/third-party/faiss/faiss/impl/io.cpp:70: Error: 'f' failed: could not open data/faiss/kotra_news_body_qwen3_article/index.faiss for reading: No such file or directory

# LLM 요약